"""As quatro entidades da convocação, e as **duas** travas que as mantêm append-only (019).

Gatilho **e** privilégio ausente, duas camadas independentes, nenhuma contornável em
desenvolvimento. O `save()` do modelo é a terceira, e é a única que um `QuerySet.update()` não
atravessa — por isso ela não basta sozinha.

O gatilho é **absoluto**, e não condicional: a convocação nasce imutável. Correção é sucessão
(`FR-272`), com motivo; não existe transição legítima que altere uma linha existente.

**Quatro tabelas e não três**, e o `AtestadoDeFatoExterno` está aqui por uma razão de forma: a
constraint `ck_desfecho_inercia_exige_atestado` é uma FK conferida pelo banco, e FK não se declara
para tabela que ainda não existe. A aplicação que o grava é da `US5`; a tabela nasce com as demais.

As quatro entram em `seguranca/papeis.py::TABELAS_APPEND_ONLY` na mesma leva — levando o total de
27 para 31. Numa base já provisionada é preciso **rodar o comando de novo** depois desta migration:
privilégio não se concede a tabela que ainda não existia.
"""

# Generated by Django 5.2.17 on 2026-09-13 00:51

import uuid

import django.db.models.deletion
from django.db import migrations, models

PROTEGER = """
CREATE FUNCTION reject_call_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'calls and their outcomes are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER convocacao_imutavel
BEFORE UPDATE OR DELETE ON convocacao_convocacao
FOR EACH ROW EXECUTE FUNCTION reject_call_mutation();

CREATE TRIGGER desfecho_da_convocacao_imutavel
BEFORE UPDATE OR DELETE ON convocacao_desfechodaconvocacao
FOR EACH ROW EXECUTE FUNCTION reject_call_mutation();

CREATE TRIGGER comunicacao_emitida_imutavel
BEFORE UPDATE OR DELETE ON convocacao_comunicacaoemitida
FOR EACH ROW EXECUTE FUNCTION reject_call_mutation();

CREATE TRIGGER atestado_de_fato_externo_imutavel
BEFORE UPDATE OR DELETE ON convocacao_atestadodefatoexterno
FOR EACH ROW EXECUTE FUNCTION reject_call_mutation();
"""

DESPROTEGER = """
DROP TRIGGER IF EXISTS atestado_de_fato_externo_imutavel ON convocacao_atestadodefatoexterno;
DROP TRIGGER IF EXISTS comunicacao_emitida_imutavel ON convocacao_comunicacaoemitida;
DROP TRIGGER IF EXISTS desfecho_da_convocacao_imutavel ON convocacao_desfechodaconvocacao;
DROP TRIGGER IF EXISTS convocacao_imutavel ON convocacao_convocacao;
DROP FUNCTION IF EXISTS reject_call_mutation();
"""


def proteger(apps, schema_editor):
    # O gatilho é PostgreSQL puro. Fora dele a migration passa sem instalar nada, e os testes que
    # dependem da garantia são pulados — é a mesma guarda que a `016` usa.
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROTEGER)


def desproteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DESPROTEGER)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inscricoes", "0004_valor_de_fato"),
        ("ocupacao", "0003_porta_de_efeitos"),
        ("processos", "0002_teto_de_inscricoes"),
        ("publicacoes", "0008_remover_ancoras"),
        ("resultados", "0005_superacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtestadoDeFatoExterno",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("NAO_ACESSO_AO_AMBIENTE", "Não acessou o ambiente"),
                            ("AUSENCIA_NA_PRIMEIRA_SEMANA", "Ausente na primeira semana"),
                            ("NAO_ENTREGA_PRESENCIAL", "Não entregou presencialmente"),
                        ],
                        max_length=40,
                    ),
                ),
                ("conclusao", models.TextField()),
                ("referencia_do_prazo", models.TextField()),
                ("atestado_por", models.CharField(max_length=255)),
                ("atestado_em", models.DateTimeField()),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atestados",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Convocacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("perfil_id", models.UUIDField()),
                ("marco_id", models.UUIDField()),
                ("lista_id", models.UUIDField(blank=True, null=True)),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("VAGA_INICIAL", "Para vaga inicial"),
                            ("SUPLENCIA", "Para vaga que vagou"),
                            ("PARA_REGULARIZAR", "Para regularizar o indeferimento"),
                        ],
                        max_length=24,
                    ),
                ),
                ("vencimento", models.DateTimeField(blank=True, null=True)),
                ("fundamento", models.TextField()),
                ("ato_de_ordenacao_id", models.UUIDField()),
                ("corte_id", models.UUIDField(blank=True, null=True)),
                ("motivo_da_sucessao", models.TextField(blank=True, default="")),
                ("criado_por", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField()),
                (
                    "apuracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convocacoes",
                        to="ocupacao.apuracaodeocupacao",
                    ),
                ),
                (
                    "convocacao_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucessoras",
                        to="convocacao.convocacao",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convocacoes",
                        to="processos.edital",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convocacoes",
                        to="inscricoes.inscricao",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convocacoes",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComunicacaoEmitida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("forma", models.CharField(max_length=32)),
                ("destinatario", models.CharField(blank=True, default="", max_length=255)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[("ENVIADA", "Enviada"), ("FALHA", "Falha")], max_length=16
                    ),
                ),
                ("detalhe_tecnico", models.TextField(blank=True, default="")),
                (
                    "convocacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comunicacoes",
                        to="convocacao.convocacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesfechoDaConvocacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("ACEITE", "Aceite"),
                            ("REGULARIZACAO", "Regularização"),
                            ("INDEFERIMENTO", "Indeferimento"),
                            ("DESISTENCIA_EXPRESSA", "Desistência expressa"),
                            ("NAO_ATENDIMENTO", "Não atendimento à convocação"),
                            ("INERCIA", "Cancelamento de matrícula por inércia"),
                            ("RECLASSIFICACAO", "Reclassificação"),
                        ],
                        max_length=24,
                    ),
                ),
                ("fundamento", models.TextField()),
                ("registrado_por", models.CharField(max_length=255)),
                ("registrado_em", models.DateTimeField()),
                (
                    "atestado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desfechos",
                        to="convocacao.atestadodefatoexterno",
                    ),
                ),
                (
                    "convocacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desfechos",
                        to="convocacao.convocacao",
                    ),
                ),
                (
                    "efeito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desfechos",
                        to="ocupacao.efeitodeocupacao",
                    ),
                ),
                (
                    "resultado_sucessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desfechos_de_convocacao",
                        to="resultados.resultadoetapa",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="atestadodefatoexterno",
            index=models.Index(fields=["inscricao"], name="ix_atestado_inscricao"),
        ),
        migrations.AddConstraint(
            model_name="atestadodefatoexterno",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "especie__in",
                        [
                            "NAO_ACESSO_AO_AMBIENTE",
                            "AUSENCIA_NA_PRIMEIRA_SEMANA",
                            "NAO_ENTREGA_PRESENCIAL",
                        ],
                    )
                ),
                name="ck_atestado_especie",
            ),
        ),
        migrations.AddConstraint(
            model_name="atestadodefatoexterno",
            constraint=models.CheckConstraint(
                condition=models.Q(("conclusao", ""), _negated=True),
                name="ck_atestado_com_conclusao",
            ),
        ),
        migrations.AddConstraint(
            model_name="atestadodefatoexterno",
            constraint=models.CheckConstraint(
                condition=models.Q(("atestado_por", ""), _negated=True),
                name="ck_atestado_com_atestante",
            ),
        ),
        migrations.AddIndex(
            model_name="convocacao",
            index=models.Index(
                fields=["edital", "perfil_id", "marco_id", "lista_id"], name="ix_convocacao_recorte"
            ),
        ),
        migrations.AddIndex(
            model_name="convocacao",
            index=models.Index(fields=["inscricao"], name="ix_convocacao_inscricao"),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("convocacao_anterior__isnull", True), ("lista_id__isnull", True)
                ),
                fields=("edital", "perfil_id", "marco_id", "inscricao"),
                name="uq_convocacao_raiz_por_recorte",
            ),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("convocacao_anterior__isnull", True), ("lista_id__isnull", False)
                ),
                fields=("edital", "perfil_id", "marco_id", "lista_id", "inscricao"),
                name="uq_convocacao_raiz_por_recorte_e_lista",
            ),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("convocacao_anterior__isnull", False)),
                fields=("convocacao_anterior",),
                name="uq_convocacao_sucessora_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("especie__in", ["VAGA_INICIAL", "SUPLENCIA", "PARA_REGULARIZAR"])
                ),
                name="ck_convocacao_especie",
            ),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("convocacao_anterior__isnull", True), ("motivo_da_sucessao", "")),
                    models.Q(
                        ("convocacao_anterior__isnull", False),
                        models.Q(("motivo_da_sucessao", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_convocacao_sucessao",
            ),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(("fundamento", ""), _negated=True),
                name="ck_convocacao_com_fundamento",
            ),
        ),
        migrations.AddIndex(
            model_name="comunicacaoemitida",
            index=models.Index(fields=["convocacao"], name="ix_comunicacao_convocacao"),
        ),
        migrations.AddConstraint(
            model_name="comunicacaoemitida",
            constraint=models.CheckConstraint(
                condition=models.Q(("resultado__in", ["ENVIADA", "FALHA"])),
                name="ck_comunicacao_resultado",
            ),
        ),
        migrations.AddConstraint(
            model_name="comunicacaoemitida",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("enviado_em__isnull", False), ("resultado", "ENVIADA")),
                    models.Q(("enviado_em__isnull", True), ("resultado", "FALHA")),
                    _connector="OR",
                ),
                name="ck_comunicacao_enviada_tem_instante",
            ),
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.UniqueConstraint(
                fields=("convocacao",), name="uq_desfecho_por_convocacao"
            ),
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "especie__in",
                        [
                            "ACEITE",
                            "REGULARIZACAO",
                            "INDEFERIMENTO",
                            "DESISTENCIA_EXPRESSA",
                            "NAO_ATENDIMENTO",
                            "INERCIA",
                            "RECLASSIFICACAO",
                        ],
                    )
                ),
                name="ck_desfecho_especie",
            ),
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("especie", "INERCIA"), _negated=True),
                    ("atestado__isnull", False),
                    _connector="OR",
                ),
                name="ck_desfecho_inercia_exige_atestado",
            ),
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("especie", "REGULARIZACAO"), _negated=True),
                    ("resultado_sucessor__isnull", False),
                    _connector="OR",
                ),
                name="ck_desfecho_regularizacao_exige_sucessor",
            ),
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(("fundamento", ""), _negated=True),
                name="ck_desfecho_com_fundamento",
            ),
        ),
        migrations.RunPython(proteger, desproteger),
    ]
