"""A mesma pessoa é chamada mais de uma vez no mesmo recorte, e o banco passa a admiti-lo (019).

**O beco que esta migration desfaz.** A `FR-283` manda o reclassificado voltar ao fim da fila e ser
chamável depois do esgotamento — e a unicidade de raiz por pessoa e recorte tornava essa segunda
chamada impossível. A única saída que sobrava era declará-la **sucessora**, e sucessão é correção de
um ato ainda pendente: ela pula as guardas de ordem, de modo que a única forma de chamá-lo furaria
a fila que ele deveria respeitar.

**O número da chamada entra na chave.** Duas chamadas da mesma pessoa continuam sendo impossíveis
**com o mesmo número** — o que a constraint existe para barrar é a duplicata, e não o retorno.

**"Uma chamada em aberto por pessoa" fica com a aplicação, e a ausência é deliberada.** A regra
depende de haver ou não desfecho, que mora em outra tabela, e índice parcial não atravessa junção.
O que o banco garante aqui é o que ele consegue garantir; o resto está em `convocar`, com recusa
nomeada.
"""

# Generated by Django 5.2.17 on 2026-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convocacao", "0001_initial"),
        ("inscricoes", "0004_valor_de_fato"),
        ("ocupacao", "0003_porta_de_efeitos"),
        ("processos", "0002_teto_de_inscricoes"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="convocacao",
            name="uq_convocacao_raiz_por_recorte",
        ),
        migrations.RemoveConstraint(
            model_name="convocacao",
            name="uq_convocacao_raiz_por_recorte_e_lista",
        ),
        migrations.AddField(
            model_name="convocacao",
            name="chamada",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("convocacao_anterior__isnull", True), ("lista_id__isnull", True)
                ),
                fields=("edital", "perfil_id", "marco_id", "inscricao", "chamada"),
                name="uq_convocacao_raiz_por_recorte",
            ),
        ),
        migrations.AddConstraint(
            model_name="convocacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("convocacao_anterior__isnull", True), ("lista_id__isnull", False)
                ),
                fields=("edital", "perfil_id", "marco_id", "lista_id", "inscricao", "chamada"),
                name="uq_convocacao_raiz_por_recorte_e_lista",
            ),
        ),
    ]
