"""O desfecho passa a suceder o desfecho, e o efeito deixa de ser anulável (019, `US5`).

**A `US5` era estruturalmente impossível no caso que ela nomeia.** O cancelamento de matrícula por
inércia *"alcança quem já ocupava e desapareceu"* — e quem já ocupava costuma ter aceitado a
chamada. Com um desfecho por convocação e nada mais, o aceite fechava a convocação e a inércia
posterior não tinha onde ser gravada. O caminho que sobrava fazia o contrário do que a norma
descreve: admitia a inércia como **primeiro** desfecho, de quem nunca aceitou nada.

**Sucessão, e não correção.** O aceite era verdadeiro quando registrado; o que mudou foi o mundo
depois dele. É a mesma forma que o `ResultadoEtapa` usa para a superação por recurso, e a `FR-273`
continua valendo: há no máximo um desfecho **vigente** por convocação.

**E o efeito deixa de ser anulável.** As sete espécies têm efeito na porta da `016` — duas incluem e
cinco excluem. Um desfecho gravado sem efeito deixaria a contagem divergente sem nada que a
explicasse, e numa tabela append-only essa linha não teria conserto: `UPDATE` é proibido, e
sucedê-la não desfaz a divergência que ela já produziu.
"""

# Generated by Django 5.2.17 on 2026-09-13 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convocacao", "0002_chamadas_sucessivas"),
        ("ocupacao", "0003_porta_de_efeitos"),
        ("resultados", "0006_regularizacao"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="desfechodaconvocacao",
            name="uq_desfecho_por_convocacao",
        ),
        migrations.AddField(
            model_name="desfechodaconvocacao",
            name="desfecho_anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sucessores",
                to="convocacao.desfechodaconvocacao",
            ),
        ),
        migrations.AddField(
            model_name="desfechodaconvocacao",
            name="motivo_da_sucessao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="desfechodaconvocacao",
            name="efeito",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="desfechos",
                to="ocupacao.efeitodeocupacao",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("desfecho_anterior__isnull", True)),
                fields=("convocacao",),
                name="uq_desfecho_por_convocacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("desfecho_anterior__isnull", False)),
                fields=("desfecho_anterior",),
                name="uq_desfecho_sucessor_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="desfechodaconvocacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("desfecho_anterior__isnull", True), ("motivo_da_sucessao", "")),
                    models.Q(
                        ("desfecho_anterior__isnull", False),
                        models.Q(("motivo_da_sucessao", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_desfecho_sucessao",
            ),
        ),
    ]
