"""A emissão por publicação passa a dizer **onde** publicou (019, `FR-287`, `FR-288`).

**O sistema não publica no site do certame**, e a `R-007` não lhe deu essa capacidade: o que ele faz
é registrar a forma que o Edital declarou. Sem a referência, a emissão por publicação gravava
`ENVIADA` sem que nada tivesse sido publicado — e no 69/2026, cujo item 7.2 convoca *"por meio de
publicação no site do Cefor"*, o prazo começava a correr contra alguém que não tinha como saber.

É a mesma forma do `referencia_do_prazo` do atestado: quem pratica o ato declara onde ele aconteceu,
e o registro guarda a declaração — em vez de o sistema afirmar um fato que não observou.
"""

# Generated by Django 5.2.17 on 2026-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convocacao", "0003_sucessao_do_desfecho"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacaoemitida",
            name="referencia_da_publicacao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="comunicacaoemitida",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("forma", "PUBLICATION"), _negated=True),
                    ("resultado", "FALHA"),
                    models.Q(("referencia_da_publicacao", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_comunicacao_publicacao_com_referencia",
            ),
        ),
    ]
