# Generated by Django 5.2.17 on 2026-08-28 11:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilVaga",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("immediate_vacancies", models.PositiveIntegerField(default=0)),
                (
                    "reserve_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("LIMITED", "Limited"),
                            ("UNLIMITED", "Unlimited"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("reserve_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("locality", models.CharField(blank=True, max_length=255)),
                ("classification_information", models.JSONField(blank=True, default=dict)),
                ("call_information", models.JSONField(blank=True, default=dict)),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfis",
                        to="processos.edital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModalidadeConcorrencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modalidades",
                        to="editais.perfilvaga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegraNormativa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("foundation", models.TextField()),
                ("version", models.CharField(max_length=50)),
                (
                    "percentage",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                ("calculation", models.JSONField(blank=True, default=dict)),
                ("rounding", models.JSONField(blank=True, default=dict)),
                ("distribution", models.JSONField(blank=True, default=dict)),
                ("call_rules", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                (
                    "modalidade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regra_normativa",
                        to="editais.modalidadeconcorrencia",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="perfilvaga",
            constraint=models.UniqueConstraint(
                fields=("edital", "code"), name="uq_perfil_edital_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="perfilvaga",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reserve_limit__isnull", True), ("reserve_type", "NONE")),
                    models.Q(("reserve_limit__isnull", False), ("reserve_type", "LIMITED")),
                    models.Q(("reserve_limit__isnull", True), ("reserve_type", "UNLIMITED")),
                    _connector="OR",
                ),
                name="ck_perfil_reserve_limit_compatible",
            ),
        ),
        migrations.AddConstraint(
            model_name="modalidadeconcorrencia",
            constraint=models.UniqueConstraint(
                fields=("perfil", "code"), name="uq_modalidade_perfil_code"
            ),
        ),
    ]
