# Generated by Django 5.2.17 on 2026-08-28 11:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0001_perfis"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cronograma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "edital",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cronograma",
                        to="processos.edital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventoCronograma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADO", "Planejado"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDO", "Concluido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PLANEJADO",
                        max_length=20,
                    ),
                ),
                (
                    "cronograma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="editais.cronograma",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "start_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cronograma", "order"), name="uq_evento_cronograma_order"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_at__isnull", True),
                            ("end_at__gte", models.F("start_at")),
                            _connector="OR",
                        ),
                        name="ck_evento_end_not_before_start",
                    ),
                ],
            },
        ),
    ]
