# Generated by Django 5.2.17 on 2026-08-30 14:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0002_cronograma"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaAvaliacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                ("eliminatory", models.BooleanField(default=False)),
                ("classificatory", models.BooleanField(default=False)),
                (
                    "minimum_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="processos.edital",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapas",
                        to="editais.eventocronograma",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edital", "order"), name="uq_etapa_edital_order"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum_score__isnull", True),
                            ("minimum_score__gte", 0),
                            _connector="OR",
                        ),
                        name="ck_etapa_minimum_score_nao_negativa",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weight__isnull", True), ("weight__gt", 0), _connector="OR"
                        ),
                        name="ck_etapa_weight_positivo",
                    ),
                ],
            },
        ),
    ]
