# Generated by Django 5.2.17 on 2026-08-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0003_etapas"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecaoEdital",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=60)),
                ("content", models.TextField()),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secoes",
                        to="processos.edital",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(fields=("edital", "key"), name="uq_secao_edital_key")
                ],
            },
        ),
    ]
