# Generated by Django 5.2.17 on 2026-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    """O que um Edital real diz sobre a vaga: atribuições, carga horária e remuneração (FR-012).

    Três `AddField` e nenhum `RunPython`: não há dado a converter. É a migration direta que a
    precondição de implantação da `007` autoriza — a feature precede o primeiro Edital de produção,
    e os Editais publicados de demonstração são recriados pela seed.

    Os três nascem com `default=""` e sem `null`, como `description` e `locality` da mesma tabela.
    Perfis existentes ganham as colunas vazias, sem perda.
    """

    dependencies = [
        ("editais", "0004_secoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilvaga",
            name="duties",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="perfilvaga",
            name="workload",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="perfilvaga",
            name="compensation",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
