# Generated by Django 5.2.17 on 2026-08-31 14:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """O contrato operacional de inscrição entra no domínio (FR-001 e FR-005 da 009).

    Duas estruturas e nenhum dado a converter. A marca do período nasce falsa em todo Evento
    existente, que é a verdade: nenhum Edital anterior designou período de inscrições, porque o
    conceito não existia. E `DocumentoExigido` nasce vazio.

    A `UniqueConstraint` parcial é o que garante um período por Cronograma sem que nenhuma camada
    precise conferir — e é também o que torna a suíte contra sqlite incapaz de exercer a regra,
    razão a mais para rodar contra PostgreSQL.
    """

    dependencies = [
        ("editais", "0005_perfil_institucional"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoExigido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True)),
                ("required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="eventocronograma",
            name="is_registration_period",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="eventocronograma",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_registration_period", True)),
                fields=("cronograma",),
                name="uq_evento_periodo_de_inscricoes",
            ),
        ),
        migrations.AddField(
            model_name="documentoexigido",
            name="edital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_exigidos",
                to="processos.edital",
            ),
        ),
        migrations.AddField(
            model_name="documentoexigido",
            name="modalidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos_exigidos",
                to="editais.modalidadeconcorrencia",
            ),
        ),
        migrations.AddField(
            model_name="documentoexigido",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos_exigidos",
                to="editais.perfilvaga",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentoexigido",
            constraint=models.UniqueConstraint(
                fields=("edital", "key"), name="uq_documento_edital_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentoexigido",
            constraint=models.UniqueConstraint(
                fields=("edital", "order"), name="uq_documento_edital_order"
            ),
        ),
    ]
