"""A Etapa passa a declarar quantas avaliações e qual a pontuação máxima (012, FR-007).

O único incremento canônico da 012, e ele acontece uma vez. As duas propriedades viajam juntas
porque a versão canônica existe para identificar **uma** forma: subir a versão com uma e
acrescentar a outra depois produziria snapshots da mesma versão com e sem a segunda — a razão que
`shared/canonical.py` já registra nos incrementos anteriores (D-001).

`null` em ambas significa "não declarado". Etapa publicada antes deste incremento não carrega as
chaves, e o que a ausência quer dizer vive num leitor só (FR-009, FR-066).
"""

# ruff: noqa: E501

# Generated by Django 5.2.17 on 2026-09-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0006_documentos_exigidos"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapaavaliacao",
            name="evaluations_per_registration",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etapaavaliacao",
            name="maximum_score",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddConstraint(
            model_name="etapaavaliacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("evaluations_per_registration__isnull", True),
                    ("evaluations_per_registration__gt", 0),
                    _connector="OR",
                ),
                name="ck_etapa_avaliacoes_positivas",
            ),
        ),
        migrations.AddConstraint(
            model_name="etapaavaliacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_score__isnull", True), ("maximum_score__gt", 0), _connector="OR"
                ),
                name="ck_etapa_maximum_score_positiva",
            ),
        ),
    ]
