"""A janela recursal do marco classificatório (018, degrau 8, FR-020, FR-030).

`{}` significa **janela não declarada** — e não janela de zero dias. É o que todo marco existente
afirma, e é uma afirmação, não uma omissão a corrigir: sem declaração o sistema não inventa prazo, e
a tempestividade continua sendo juízo de admissibilidade motivado (FR-028).
"""

# Generated by Django 5.2.17 on 2026-09-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0010_marco_classificatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="marcoclassificatorio",
            name="janela_recursal",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
