"""Os Anexos do Edital (020, FR-001, FR-020).

Duas tabelas e um campo. A identidade normativa do Anexo, os bytes do artefato, e o vínculo do
Documento Exigido com o modelo que o Edital fornece.

A imutabilidade do artefato **não** vem daqui: `congelado_em` nasce nulo e nada nesta migration o
protege. A trigger condicional é a `0013`, e as duas são separadas pela mesma razão que a `0007`
das publicações é separada da `0001` — proteger no banco é decisão própria, e lê-la junto com a
criação da tabela esconderia que ela existe.
"""

# Generated by Django 5.2.17 on 2026-09-07 21:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0011_janela_recursal"),
        ("processos", "0002_teto_de_inscricoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtefatoAnexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("bytes", models.BinaryField()),
                ("content_type", models.CharField(default="application/pdf", max_length=100)),
                ("tamanho", models.PositiveBigIntegerField()),
                ("document_hash", models.CharField(db_index=True, max_length=64)),
                ("nome_original", models.CharField(max_length=255)),
                ("enviado_por", models.CharField(max_length=255)),
                ("enviado_em", models.DateTimeField()),
                ("congelado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["enviado_em", "id"],
            },
        ),
        migrations.CreateModel(
            name="AnexoEdital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rotulo", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anexos",
                        to="processos.edital",
                    ),
                ),
                (
                    "artefato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anexos",
                        to="editais.artefatoanexo",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="documentoexigido",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisitos",
                to="editais.anexoedital",
            ),
        ),
        migrations.AddConstraint(
            model_name="anexoedital",
            constraint=models.UniqueConstraint(
                fields=("edital", "order"), name="uq_anexo_edital_order"
            ),
        ),
    ]
