# Generated by Django 5.2.17 on 2026-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0013_congelamento_do_artefato"),
    ]

    operations = [
        migrations.AddField(
            model_name="marcoclassificatorio",
            name="metodo_de_sorteio",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
