# Generated by Django 5.2.17 on 2026-09-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0014_metodo_de_sorteio"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventocronograma",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
