# Generated by Django 5.2.17 on 2026-09-10 19:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """A tabela do quadro de vagas (025). **Aditiva**: cria, e não altera nem remove nada.

    Nenhum campo da `RegraNormativa` é tocado — `percentage`, `calculation`, `rounding` e
    `distribution` seguem publicados e intactos (FR-174, D-003). A Constituição proíbe migration
    que apague dado normativo, e esta não tem o que apagar: a coleção nasce agora.
    """

    dependencies = [
        ("editais", "0015_local_do_evento"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinhaDoQuadroDeVagas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("vagas_imediatas", models.PositiveIntegerField()),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "modalidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linhas_do_quadro",
                        to="editais.modalidadeconcorrencia",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quadro_de_vagas",
                        to="editais.perfilvaga",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("modalidade__isnull", False)),
                        fields=("perfil", "modalidade"),
                        name="uq_linha_por_modalidade",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("modalidade__isnull", True)),
                        fields=("perfil",),
                        name="uq_linha_geral_por_perfil",
                    ),
                ],
            },
        ),
    ]
