# Generated by Django 5.2.17 on 2026-09-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0016_quadro_de_vagas"),
    ]

    operations = [
        migrations.AddField(
            model_name="marcoclassificatorio",
            name="regra_de_corte",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
