# Generated by Django 5.2.17 on 2026-09-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0017_regra_de_corte"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilvaga",
            name="modalidade_ampla_concorrencia",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
