# Generated by Django 5.2.17 on 2026-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0018_ampla_concorrencia_declarada"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilvaga",
            name="especie_de_reversao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ON_EXHAUSTION", "Só quando a lista reservada esgota"),
                    ("ON_BALANCE", "A quantidade que ficou sem preencher"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
