# Generated by Django 5.2.17 on 2026-09-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0019_perfilvaga_especie_de_reversao"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilvaga",
            name="forma_de_convocacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLICATION", "Por publicação no endereço eletrônico do certame"),
                    ("INDIVIDUAL_MESSAGE", "Por mensagem individual à pessoa convocada"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
