# Generated by Django 5.2.17 on 2026-09-17 16:42
#
# A forma de produção da ordem do marco (030, FR-413). **Acrescenta coluna e não percorre linha
# nenhuma**: `""` é o valor de todo marco já existente, e é a afirmação certa sobre ele — a
# capacidade não existia, ninguém a declarou, e os leitores derivam da ausência o comportamento de
# sempre. Preencher aqui reescreveria conteúdo normativo de Edital publicado, que o princípio II
# proíbe (FR-431, SC-142).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0020_forma_de_convocacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="marcoclassificatorio",
            name="forma_da_ordem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POR_PONTUACAO", "Por Pontuacao"),
                    ("POR_SORTEIO", "Por Sorteio"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
