# Generated by Django 5.2.17 on 2026-09-26 00:59
#
# O recorte transversal do Documento Exigido (044, FR-700). **Acrescenta coluna e não percorre linha
# nenhuma**: `""` é o valor de todo documento já existente, e é a afirmação certa sobre ele — a
# capacidade não existia, e ninguém recortou por código. A restrição torna o código exclusivo com
# Perfil e Modalidade exata (D-006), e nenhuma linha existente a viola, porque todas têm `""`.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0021_forma_da_ordem"),
        ("processos", "0004_metodo_de_sorteio_comum"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoexigido",
            name="modalidade_codigo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="documentoexigido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("modalidade_codigo", ""),
                    models.Q(("modalidade__isnull", True), ("perfil__isnull", True)),
                    _connector="OR",
                ),
                name="ck_documento_recorte_exclusivo",
            ),
        ),
    ]
