# Generated by Django 5.2.17 on 2026-08-28 11:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


def protect_publications(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION reject_publication_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'published records are append-only';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER publicacao_append_only
        BEFORE UPDATE OR DELETE ON publicacoes_publicacao
        FOR EACH ROW EXECUTE FUNCTION reject_publication_mutation();
        CREATE TRIGGER documento_publicado_append_only
        BEFORE UPDATE OR DELETE ON publicacoes_documentopublicado
        FOR EACH ROW EXECUTE FUNCTION reject_publication_mutation();
        """
    )


def unprotect_publications(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS publicacao_append_only ON publicacoes_publicacao;
        DROP TRIGGER IF EXISTS documento_publicado_append_only ON publicacoes_documentopublicado;
        DROP FUNCTION IF EXISTS reject_publication_mutation();
        """
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publicacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("publication_order", models.PositiveBigIntegerField()),
                ("published_at", models.DateTimeField()),
                ("effective_at", models.DateTimeField()),
                ("content_hash", models.CharField(max_length=64)),
                ("canonical_content", models.BinaryField()),
                ("canonical_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("published_by", models.CharField(max_length=255)),
                ("signatory_id", models.UUIDField()),
                ("signatory_name", models.CharField(max_length=255)),
                ("signatory_role", models.CharField(max_length=255)),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publicacoes",
                        to="processos.edital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoPublicado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("bytes", models.BinaryField()),
                ("content_type", models.CharField(default="application/pdf", max_length=100)),
                ("document_hash", models.CharField(max_length=64, unique=True)),
                (
                    "publicacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documento",
                        to="publicacoes.publicacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevisaoEdital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("edital_revision", models.PositiveBigIntegerField()),
                ("content", models.JSONField()),
                ("canonical_content", models.BinaryField()),
                ("canonical_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("content_hash", models.CharField(max_length=64)),
                ("prepared_by", models.CharField(max_length=255)),
                ("submitted_at", models.DateTimeField()),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisoes",
                        to="processos.edital",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publicacao",
            name="revisao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publicacao",
                to="publicacoes.revisaoedital",
            ),
        ),
        migrations.CreateModel(
            name="Homologacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("homologated_by", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("homologated_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_by", models.CharField(blank=True, max_length=255)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "revisao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="homologacoes",
                        to="publicacoes.revisaoedital",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="revisaoedital",
            constraint=models.UniqueConstraint(
                fields=("edital", "edital_revision"), name="uq_revisao_edital_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicacao",
            constraint=models.UniqueConstraint(
                fields=("edital", "publication_order"), name="uq_publicacao_edital_order"
            ),
        ),
        migrations.RunPython(protect_publications, unprotect_publications),
    ]
