# Generated by Django 5.2.17 on 2026-08-28 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='revisao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicacao', to='publicacoes.revisaoedital'),
        ),
        migrations.CreateModel(
            name='VersaoConsolidada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('materialized_at', models.DateTimeField()),
                ('content', models.JSONField()),
                ('canonical_content', models.BinaryField()),
                ('content_hash', models.CharField(max_length=64)),
                ('applied_publications', models.JSONField(default=list)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes_consolidadas', to='processos.edital')),
                ('source_publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicacoes.publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Retificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('justification', models.TextField()),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboracao'), ('EM_REVISAO', 'Em Revisao'), ('HOMOLOGADA', 'Homologada'), ('PUBLICADA', 'Publicada'), ('CANCELADA', 'Cancelada')], default='EM_ELABORACAO', max_length=20)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('homologated_by', models.CharField(blank=True, max_length=255)),
                ('homologated_at', models.DateTimeField(blank=True, null=True)),
                ('homologation_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes', to='processos.edital')),
                ('publication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacao', to='publicacoes.publicacao')),
                ('base_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicacoes.versaoconsolidada')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenienciaConteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_path', models.CharField(max_length=1000)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicacoes.publicacao')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveniencias', to='publicacoes.versaoconsolidada')),
            ],
        ),
        migrations.CreateModel(
            name='AlteracaoNormativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_path', models.CharField(max_length=1000)),
                ('operation', models.CharField(max_length=10)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('expected_previous_hash', models.CharField(blank=True, max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('retificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='publicacoes.retificacao')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('retificacao', 'order'), name='uq_alteracao_order')],
            },
        ),
        migrations.AddIndex(
            model_name='versaoconsolidada',
            index=models.Index(fields=['edital', 'valid_from', 'materialized_at'], name='publicacoes_edital__4e5e8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='provenienciaconteudo',
            constraint=models.UniqueConstraint(fields=('versao', 'target_path'), name='uq_proveniencia_path'),
        ),
    ]
