# Generated by Django 5.2.17 on 2026-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicacoes", "0002_retificacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="retificacao",
            name="return_reason",
            field=models.TextField(blank=True),
        ),
    ]
