# Generated by Django 5.2.17 on 2026-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """Devolução da Retificação para elaboração.

    Renumerada de 0003 para 0004 na integração: a outra linha de trabalho já ocupava 0003
    com a remoção da unicidade de document_hash. Duas migrations 0003 no mesmo app criariam
    dois leaf nodes e quebrariam todo migrate.
    """

    dependencies = [
        ("publicacoes", "0003_documento_publicado_hash_nao_unico"),
    ]

    operations = [
        migrations.AddField(
            model_name="retificacao",
            name="return_reason",
            field=models.TextField(blank=True),
        ),
    ]
