# Generated by Django 5.2.17 on 2026-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicacoes", "0004_devolucao_retificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="alteracaonormativa",
            name="expected_anchors",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
