# Generated by Django 5.2.17 on 2026-08-31 17:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """A Inscrição, com as três invariantes no banco (FR-028, FR-062 e o estado submetido).

    A unicidade por identidade, Edital e Perfil vale em **qualquer** estado: rascunho duplicado e
    envio duplicado são a mesma violação, e uma restrição só responde pelas duas. O protocolo é
    único entre os que existem. E `SUBMETIDA` só é alcançável com instante, protocolo, versão
    aceita e aceite das declarações — o que a aplicação garante, o banco também.
    """

    initial = True

    dependencies = [
        ("processos", "0001_initial"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identity_subject", models.CharField(max_length=255)),
                ("profile_id", models.UUIDField()),
                ("modality_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("SUBMETIDA", "Submetida")],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("nome", models.CharField(blank=True, max_length=255)),
                ("cpf", models.CharField(blank=True, max_length=20)),
                ("cpf_normalizado", models.CharField(blank=True, max_length=11)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("declaracoes_aceitas_em", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("protocolo", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField()),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="processos.edital",
                    ),
                ),
                (
                    "versao_aceita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes_aceitas",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
                (
                    "versao_reconhecida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes_reconhecidas",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["edital", "status"], name="inscricoes__edital__601b0f_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("identity_subject", "edital", "profile_id"),
                        name="uq_inscricao_identidade_edital_perfil",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("protocolo", ""), _negated=True),
                        fields=("protocolo",),
                        name="uq_inscricao_protocolo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "RASCUNHO"),
                            models.Q(
                                ("declaracoes_aceitas_em__isnull", False),
                                ("status", "SUBMETIDA"),
                                ("submitted_at__isnull", False),
                                ("versao_aceita__isnull", False),
                                models.Q(("protocolo", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_inscricao_submetida_completa",
                    ),
                ],
            },
        ),
    ]
