# Generated by Django 5.2.17 on 2026-08-31 18:03

import uuid

import django.db.models.deletion
from django.db import migrations, models

import processo_seletivo.inscricoes.storage


class Migration(migrations.Migration):
    """O Documento Submetido, ligado ao requisito que atende (FR-043, FR-044).

    Um arquivo por requisito, garantido no banco — substituir é sobrescrever, e não acumular
    versões que ninguém saberia qual vale. O armazenamento entra como classe, e a raiz não: ela é
    configuração da implantação, e gravá-la aqui faria o histórico do esquema depender de onde o
    processo rodou.
    """

    dependencies = [
        ("inscricoes", "0001_inscricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoSubmetido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requirement_id", models.UUIDField()),
                (
                    "arquivo",
                    models.FileField(
                        max_length=255,
                        storage=processo_seletivo.inscricoes.storage.ArmazenamentoPrivado(),
                        upload_to=processo_seletivo.inscricoes.storage.caminho_do_documento,
                    ),
                ),
                ("nome_original", models.CharField(max_length=255)),
                ("tamanho", models.PositiveBigIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField()),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inscricao", "requirement_id"),
                        name="uq_documento_inscricao_requisito",
                    )
                ],
            },
        ),
    ]
