# Generated by Django 5.2.17 on 2026-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """A restrição de CPF sobre inscrição enviada — depois da verificação, nunca antes.

    A ordem não é preferência. `identidade.0002` percorre as inscrições e **interrompe** quando
    encontra uma enviada sem CPF utilizável, enumerando o que precisa de tratamento. Instalar esta
    restrição antes disso faria a implantação falhar no `ALTER TABLE`, com a mensagem do banco no
    lugar do relatório — e quem a lesse não saberia quais linhas corrigir.

    São duas migrações, e não uma, porque a restrição incide sobre `Inscricao`: restrição de
    modelo mora no app que a define.
    """

    dependencies = [
        ('inscricoes', '0002_documento_submetido'),
        ('identidade', '0002_reconciliacao'),
        ('processos', '0001_initial'),
        ('publicacoes', '0008_remover_ancoras'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "RASCUNHO"),
                    ("cpf_normalizado__regex", r"^[0-9]{11}$"),
                    _connector="OR",
                ),
                name="ck_inscricao_submetida_com_cpf",
            ),
        ),
    ]
