# Generated by Django 5.2.17 on 2026-09-05 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_cpf_na_submetida'),
        ('publicacoes', '0008_remover_ancoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorDeFato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fato_id', models.UUIDField()),
                ('valor_data', models.DateField(blank=True, null=True)),
                ('valor_inteiro', models.IntegerField(blank=True, null=True)),
                ('congelado_em', models.DateTimeField()),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatos', to='inscricoes.inscricao')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatos_congelados', to='publicacoes.versaoconsolidada')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('inscricao', 'fato_id'), name='uq_valor_por_inscricao_fato'), models.CheckConstraint(condition=models.Q(models.Q(('valor_data__isnull', False), ('valor_inteiro__isnull', True)), models.Q(('valor_data__isnull', True), ('valor_inteiro__isnull', False)), _connector='OR'), name='ck_valor_conforme_tipo')],
            },
        ),
    ]
