# Generated by Django 5.2.17 on 2026-09-26 01:14
"""A lista exigida da inscrição, suas constraints e suas duas triggers (044, FR-714, FR-715).

**Nasce append-only, nas duas camadas**: a trigger recusa a mutação mesmo de quem tem privilégio,
e o papel de runtime não recebe `UPDATE` nem `DELETE` — este segundo vem de `TABELAS_APPEND_ONLY`,
em `seguranca/papeis.py`, e é por isso que `make preparar` precisa rodar **de novo** depois desta
migration.

**A trigger de coerência confere o que `CHECK` não alcança**, porque `CHECK` não atravessa
tabelas: a inscrição está enviada, a versão da lista é a que ela aceitou, e o instante é o do envio.
É o que prende a lista ao ato que a produziu — inclusive quando uma Retificação é publicada no meio
do envio (FR-714).

O que ela **não** confere é que a lista nasceu *durante* o envio: quem copiar `submitted_at` para
`gravada_em` passa. As duas formas de conferir isso no banco foram pesadas e descartadas (R-005) —
`xmin` contra a transação corrente falha porque o envio grava sob *savepoint*, e cortar pelo
instante desta migration recusaria a semente e as fixtures, que põem o envio no passado de
propósito. A garantia de que nenhuma inscrição antiga ganha lista escrita depois é da aplicação
(D-004), e esta migration não percorre linha nenhuma.
"""

import uuid

import django.db.models.deletion
from django.db import migrations, models

PROTEGER = """
CREATE OR REPLACE FUNCTION reject_required_list_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'required document lists are append-only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER item_da_lista_exigida_append_only
BEFORE UPDATE OR DELETE ON inscricoes_itemdalistaexigida
FOR EACH ROW EXECUTE FUNCTION reject_required_list_mutation();

CREATE OR REPLACE FUNCTION check_required_list_coherence() RETURNS trigger AS $$
DECLARE
    alvo RECORD;
BEGIN
    SELECT i.status, i.versao_aceita_id, i.submitted_at
      INTO alvo
      FROM inscricoes_inscricao i
     WHERE i.id = NEW.inscricao_id;
    IF NOT FOUND OR alvo.status <> 'SUBMETIDA' THEN
        RAISE EXCEPTION 'required document list for a registration that was not submitted';
    END IF;
    IF alvo.versao_aceita_id IS DISTINCT FROM NEW.versao_id THEN
        RAISE EXCEPTION 'required document list from a version the registration did not accept';
    END IF;
    IF alvo.submitted_at IS DISTINCT FROM NEW.gravada_em THEN
        RAISE EXCEPTION 'required document list recorded at another instant than the submission';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER item_da_lista_exigida_coerente
BEFORE INSERT ON inscricoes_itemdalistaexigida
FOR EACH ROW EXECUTE FUNCTION check_required_list_coherence();
"""

DESPROTEGER = """
DROP TRIGGER IF EXISTS item_da_lista_exigida_coerente ON inscricoes_itemdalistaexigida;
DROP FUNCTION IF EXISTS check_required_list_coherence();
DROP TRIGGER IF EXISTS item_da_lista_exigida_append_only ON inscricoes_itemdalistaexigida;
DROP FUNCTION IF EXISTS reject_required_list_mutation();
"""


def proteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROTEGER)


def desproteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DESPROTEGER)


class Migration(migrations.Migration):
    dependencies = [
        ("inscricoes", "0004_valor_de_fato"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemDaListaExigida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requisito_id", models.UUIDField()),
                ("chave", models.CharField(max_length=100)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("OBRIGATORIO", "Obrigatorio"),
                            ("FACULTATIVO", "Facultativo"),
                            ("NAO_SE_APLICA", "Nao Se Aplica"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "forma_do_recorte",
                    models.CharField(
                        choices=[
                            ("TODOS", "Todos"),
                            ("PERFIL", "Perfil"),
                            ("PERFIL_E_MODALIDADE", "Perfil E Modalidade"),
                            ("MODALIDADE_EM_TODOS_OS_PERFIS", "Modalidade Em Todos Os Perfis"),
                            (
                                "TODOS_COM_MODALIDADE_DE_UM_PERFIL",
                                "Todos Com Modalidade De Um Perfil",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("perfil_id", models.UUIDField(blank=True, null=True)),
                ("modalidade_id", models.UUIDField(blank=True, null=True)),
                ("modalidade_codigo", models.CharField(blank=True, default="", max_length=100)),
                ("divergente_do_publicado", models.BooleanField(default=False)),
                ("gravada_em", models.DateTimeField()),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lista_exigida",
                        to="inscricoes.inscricao",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listas_exigidas",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
            options={
                "ordering": ["gravada_em", "id"],
                "indexes": [
                    models.Index(fields=["inscricao"], name="inscricoes__inscric_7f6e9c_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inscricao", "requisito_id"), name="uq_item_da_lista_por_requisito"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("situacao__in", ["OBRIGATORIO", "FACULTATIVO", "NAO_SE_APLICA"])
                        ),
                        name="ck_item_da_lista_situacao",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("forma_do_recorte", "TODOS"),
                                ("modalidade_codigo", ""),
                                ("modalidade_id__isnull", True),
                                ("perfil_id__isnull", True),
                            ),
                            models.Q(
                                ("forma_do_recorte", "PERFIL"),
                                ("modalidade_codigo", ""),
                                ("modalidade_id__isnull", True),
                                ("perfil_id__isnull", False),
                            ),
                            models.Q(
                                ("forma_do_recorte", "PERFIL_E_MODALIDADE"),
                                ("modalidade_codigo", ""),
                                ("modalidade_id__isnull", False),
                                ("perfil_id__isnull", False),
                            ),
                            models.Q(
                                ("forma_do_recorte", "MODALIDADE_EM_TODOS_OS_PERFIS"),
                                ("modalidade_id__isnull", True),
                                ("perfil_id__isnull", True),
                                models.Q(("modalidade_codigo", ""), _negated=True),
                            ),
                            models.Q(
                                ("forma_do_recorte", "TODOS_COM_MODALIDADE_DE_UM_PERFIL"),
                                ("modalidade_codigo", ""),
                                ("modalidade_id__isnull", False),
                                ("perfil_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_item_da_lista_forma",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("divergente_do_publicado", False),
                            ("forma_do_recorte", "TODOS_COM_MODALIDADE_DE_UM_PERFIL"),
                            _connector="OR",
                        ),
                        name="ck_item_da_lista_divergencia",
                    ),
                ],
            },
        ),
        migrations.RunPython(proteger, desproteger),
    ]
