# Generated by Django 5.2.17 on 2026-08-28 11:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AtoAdministrativo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("aggregate_type", models.CharField(max_length=50)),
                ("aggregate_id", models.UUIDField()),
                ("operation", models.CharField(max_length=50)),
                ("actor_subject", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("occurred_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProcessoSeletivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("institution_scope", models.CharField(max_length=100)),
                ("institutional_code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ELABORACAO", "Em Elaboracao"),
                            ("ATIVO", "Ativo"),
                            ("ENCERRADO", "Encerrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="EM_ELABORACAO",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.CharField(max_length=255)),
                ("last_changed_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution_scope", "institutional_code"),
                        name="uq_processo_scope_institutional_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Edital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("institution_scope", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=50)),
                ("year", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ELABORACAO", "Em Elaboracao"),
                            ("EM_REVISAO", "Em Revisao"),
                            ("HOMOLOGADO", "Homologado"),
                            ("PUBLICADO", "Publicado"),
                            ("ENCERRADO", "Encerrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="EM_ELABORACAO",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("next_publication_order", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.CharField(max_length=255)),
                ("last_edited_by", models.CharField(max_length=255)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editais",
                        to="processos.processoseletivo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["processo", "status"], name="processos_e_process_53f13a_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution_scope", "number", "year"),
                        name="uq_edital_scope_number_year",
                    )
                ],
            },
        ),
    ]
