# Generated by Django 5.2.17 on 2026-09-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processos", "0002_teto_de_inscricoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="requerimento_declaracao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="edital",
            name="requerimento_momento",
            field=models.CharField(
                blank=True,
                choices=[("AT_ENROLLMENT", "Na inscrição"), ("AT_CALL", "Na convocação")],
                default="",
                max_length=32,
            ),
        ),
    ]
