# Generated by Django 5.2.17 on 2026-09-17
#
# O método do sorteio comum ao Edital (030, FR-429). **Acrescenta coluna e não percorre linha
# nenhuma**: `{}` é o valor de todo Edital existente, e é a afirmação certa sobre ele — a
# capacidade não existia, ninguém a declarou, e cada marco continua carregando o método literal
# que publicou. A resolução só alcança marco **sem** método próprio, que é estado que nenhum
# Edital publicado tem (FR-431, SC-142).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # **`0003`, e não `0002`.** A `029` entrou na `main` depois de esta migration ser escrita,
        # e as duas nasceram como `0003`: dois leaf nodes no mesmo app quebram qualquer `migrate`,
        # e o Git não vê a colisão porque os arquivos têm nomes diferentes. Renumerada no rebase,
        # e não reescrita — nenhuma das duas foi aplicada em produção ainda.
        ("processos", "0003_requerimento_de_matricula"),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="metodo_de_sorteio_comum",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
