# Generated by Django 5.2.17 on 2026-08-28 11:00

import os
import uuid

from django.db import migrations, models


def protect_audit_log(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION reject_audit_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit records are append-only';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER auditoria_append_only
        BEFORE UPDATE OR DELETE ON auditoria_registroauditoria
        FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();
        """
    )
    runtime_role = os.getenv("DB_RUNTIME_USER")
    if runtime_role:
        quoted_role = schema_editor.connection.ops.quote_name(runtime_role)
        schema_editor.execute(
            f"GRANT SELECT, INSERT ON auditoria_registroauditoria TO {quoted_role};"
        )
        schema_editor.execute(
            f"REVOKE UPDATE, DELETE ON auditoria_registroauditoria FROM {quoted_role};"
        )


def unprotect_audit_log(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS auditoria_append_only ON auditoria_registroauditoria;
        DROP FUNCTION IF EXISTS reject_audit_mutation();
        """
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("institution_scope", models.CharField(max_length=100)),
                ("actor_subject", models.CharField(max_length=255)),
                ("operation", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("result_type", models.CharField(blank=True, max_length=100)),
                ("result_id", models.UUIDField(null=True)),
                ("response_status", models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution_scope", "actor_subject", "operation", "key"),
                        name="uq_idempotency_scope_actor_operation_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("actor_subject", models.CharField(max_length=255)),
                ("permission", models.CharField(max_length=100)),
                ("institution_scope", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=100)),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.UUIDField()),
                ("previous_state", models.CharField(blank=True, max_length=50)),
                ("new_state", models.CharField(blank=True, max_length=50)),
                ("previous_revision", models.PositiveBigIntegerField(null=True)),
                ("new_revision", models.PositiveBigIntegerField(null=True)),
                ("reason", models.TextField(blank=True)),
                ("correlation_id", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "occurred_at"],
                        name="auditoria_r_aggrega_2b677f_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(protect_audit_log, unprotect_audit_log),
    ]
