"""A reserva de idempotência passa a guardar o desfecho de um ato em lote (012, FR-084).

Ato de resultado singular já era coberto: `result_id` aponta para o objeto, e a repetição o
devolve. Lote não tem objeto único — tem resultado —, e sem guardá-lo a repetição respondia zero
atribuídas e zero recusadas, contradizendo o resultado declarado de FR-097.

Coluna anulável e aditiva: nada do que já existe muda, e todo ato singular continua com ela vazia.
"""

# Generated by Django 5.2.17 on 2026-09-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencyrecord",
            name="result_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
