# Generated by Django 5.2.17 on 2026-09-01 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroComissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_subject', models.CharField(max_length=255)),
                ('display_label', models.CharField(blank=True, max_length=255)),
                ('funcao', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField()),
                ('criado_por', models.CharField(max_length=255)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
                ('inativado_por', models.CharField(blank=True, max_length=255)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros_da_comissao', to='processos.processoseletivo')),
            ],
            options={
                'ordering': ['funcao', 'identity_subject'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoEtapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etapa_id', models.UUIDField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField()),
                ('criado_por', models.CharField(max_length=255)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
                ('inativado_por', models.CharField(blank=True, max_length=255)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='processos.edital')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='comissoes.membrocomissao')),
            ],
        ),
        migrations.AddIndex(
            model_name='membrocomissao',
            index=models.Index(fields=['processo', 'ativo'], name='comissoes_m_process_e6eea9_idx'),
        ),
        migrations.AddConstraint(
            model_name='membrocomissao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('processo', 'identity_subject'), name='uq_membro_ativo_por_processo'),
        ),
        migrations.AddConstraint(
            model_name='membrocomissao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ativo', True), ('inativado_em__isnull', True)), models.Q(('ativo', False), ('inativado_em__isnull', False)), _connector='OR'), name='ck_membro_inativacao_completa'),
        ),
        migrations.AddIndex(
            model_name='alocacaoetapa',
            index=models.Index(fields=['edital', 'etapa_id', 'ativo'], name='comissoes_a_edital__3afa12_idx'),
        ),
        migrations.AddConstraint(
            model_name='alocacaoetapa',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('membro', 'edital', 'etapa_id'), name='uq_alocacao_ativa_por_membro_e_etapa'),
        ),
        migrations.AddConstraint(
            model_name='alocacaoetapa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ativo', True), ('inativado_em__isnull', True)), models.Q(('ativo', False), ('inativado_em__isnull', False)), _connector='OR'), name='ck_alocacao_inativacao_completa'),
        ),
    ]
