"""As duas entidades da ocupação, e as **duas** travas que as mantêm append-only (016, `D-008`).

Gatilho **e** privilégio ausente, duas camadas independentes, nenhuma contornável em
desenvolvimento. O `save()` do modelo é a terceira, e é a única que um `QuerySet.update()` não
atravessa — por isso ela não basta sozinha.

O gatilho é **absoluto**, e não condicional: a apuração nasce imutável. Sucessão cria linha nova;
não existe transição legítima que altere uma linha existente.

O privilégio é retirado por `provisionar_papeis`, e as duas tabelas entram em
`seguranca/papeis.py::TABELAS_APPEND_ONLY` na mesma leva — levando o total de 24 para 26. Numa base
já provisionada é preciso **rodar o comando de novo** depois desta migration: privilégio não se
concede a tabela que ainda não existia.
"""

# Generated by Django 5.2.17 on 2026-09-12 13:47

import uuid

import django.db.models.deletion
from django.db import migrations, models

PROTEGER = """
CREATE FUNCTION reject_occupancy_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'occupancy appraisals are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER apuracao_imutavel
BEFORE UPDATE OR DELETE ON ocupacao_apuracaodeocupacao
FOR EACH ROW EXECUTE FUNCTION reject_occupancy_mutation();

CREATE TRIGGER movimento_de_vaga_imutavel
BEFORE UPDATE OR DELETE ON ocupacao_movimentodevaga
FOR EACH ROW EXECUTE FUNCTION reject_occupancy_mutation();
"""

DESPROTEGER = """
DROP TRIGGER IF EXISTS movimento_de_vaga_imutavel ON ocupacao_movimentodevaga;
DROP TRIGGER IF EXISTS apuracao_imutavel ON ocupacao_apuracaodeocupacao;
DROP FUNCTION IF EXISTS reject_occupancy_mutation();
"""


def proteger(apps, schema_editor):
    # O gatilho é PostgreSQL puro. Fora dele a migration passa sem instalar nada, e os testes que
    # dependem da garantia são pulados — é a mesma guarda que a `014` usa.
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROTEGER)


def desproteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DESPROTEGER)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classificacao", "0006_corte"),
        ("inscricoes", "0004_valor_de_fato"),
        ("processos", "0002_teto_de_inscricoes"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApuracaoDeOcupacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("perfil_id", models.UUIDField()),
                ("marco_id", models.UUIDField()),
                ("lista_id", models.UUIDField(blank=True, null=True)),
                ("motivo_da_sucessao", models.TextField(blank=True, default="")),
                ("publicadas", models.PositiveIntegerField()),
                ("efetivas", models.PositiveIntegerField()),
                ("ocupadas", models.PositiveIntegerField()),
                ("linha_do_quadro_id", models.UUIDField(blank=True, null=True)),
                ("universo", models.JSONField(default=dict)),
                ("emitida_por", models.CharField(max_length=255)),
                ("emitida_em", models.DateTimeField()),
                (
                    "apuracao_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucessoras",
                        to="ocupacao.apuracaodeocupacao",
                    ),
                ),
                (
                    "ato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apuracoes",
                        to="classificacao.atodeordenacao",
                    ),
                ),
                (
                    "corte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apuracoes",
                        to="classificacao.corte",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apuracoes",
                        to="processos.edital",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apuracoes",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentoDeVaga",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("REVERSAO_DE_COTA", "Reversão de cota"),
                            (
                                "LIBERACAO_POR_CONCOMITANCIA",
                                "Liberação por concorrência concomitante",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("origem_lista_id", models.UUIDField(blank=True, null=True)),
                ("destino_lista_id", models.UUIDField(blank=True, null=True)),
                ("quantidade", models.PositiveIntegerField()),
                ("causa", models.TextField()),
                ("registrado_por", models.CharField(max_length=255)),
                ("registrado_em", models.DateTimeField()),
                (
                    "apuracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentos",
                        to="ocupacao.apuracaodeocupacao",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentos_de_vaga",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="apuracaodeocupacao",
            index=models.Index(
                fields=["edital", "perfil_id", "marco_id", "lista_id"], name="ix_apuracao_recorte"
            ),
        ),
        migrations.AddConstraint(
            model_name="apuracaodeocupacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("apuracao_anterior__isnull", True), ("lista_id__isnull", True)),
                fields=("edital", "perfil_id", "marco_id"),
                name="uq_apuracao_primeira_por_marco",
            ),
        ),
        migrations.AddConstraint(
            model_name="apuracaodeocupacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("apuracao_anterior__isnull", True), ("lista_id__isnull", False)
                ),
                fields=("edital", "perfil_id", "marco_id", "lista_id"),
                name="uq_apuracao_primeira_por_marco_e_lista",
            ),
        ),
        migrations.AddConstraint(
            model_name="apuracaodeocupacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("apuracao_anterior__isnull", False)),
                fields=("apuracao_anterior",),
                name="uq_apuracao_sucessora_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="apuracaodeocupacao",
            constraint=models.CheckConstraint(
                condition=models.Q(("ocupadas__lte", models.F("efetivas"))),
                name="ck_apuracao_ocupadas_no_limite",
            ),
        ),
        migrations.AddConstraint(
            model_name="apuracaodeocupacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("apuracao_anterior__isnull", True),
                    models.Q(("motivo_da_sucessao", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_apuracao_sucessao_com_motivo",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentodevaga",
            index=models.Index(fields=["destino_lista_id"], name="ix_movimento_destino"),
        ),
        migrations.AddConstraint(
            model_name="movimentodevaga",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gt", 0)), name="ck_movimento_quantidade_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentodevaga",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("destino_lista_id__isnull", False), ("origem_lista_id__isnull", True)
                    ),
                    models.Q(
                        ("destino_lista_id__isnull", True), ("origem_lista_id__isnull", False)
                    ),
                    models.Q(
                        ("destino_lista_id__isnull", False),
                        ("origem_lista_id__isnull", False),
                        models.Q(("origem_lista_id", models.F("destino_lista_id")), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_movimento_recortes_distintos",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentodevaga",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("especie", "REVERSAO_DE_COTA"), ("inscricao__isnull", True)),
                    models.Q(
                        ("especie", "LIBERACAO_POR_CONCOMITANCIA"), ("inscricao__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_movimento_inscricao_conforme_especie",
            ),
        ),
        migrations.RunPython(proteger, desproteger),
    ]
