"""A concorrência concomitante não é movimento de vaga — e por isso a coluna sai (016, `FR-252`).

**O achado que esta migration executa.** A primeira modelagem tratou o item 8.9 do 28/2026 como o
sentido oposto da reversão: uma quantidade saindo da ampla e entrando na reservada. O Edital diz
outra coisa, com estas palavras: o autodeclarado sorteado dentro das vagas de ampla *"não será
computado para efeito do preenchimento das vagas reservadas, isto é, não constará na lista de
classificados como autodeclarados, abrindo vaga para o próximo suplente autodeclarado"*.

Quantidade nenhuma muda de lista. A reservada continua com as vagas que publicou, e o que muda é
que ele não conta como tendo ocupado uma delas. Modelar como transferência produzia, num Perfil de
2 amplas e 1 reservada, efetivas de 1 e 2 — onde o Edital manda 2 e 1.

A exclusão passou para o cálculo de `ocupadas`, e com ela saem a espécie `LIBERACAO`, a coluna
`inscricao` e a constraint que condicionava uma à outra.

**Nenhum dado normativo se perde**: nenhum Edital publicado declarou reversão até aqui, e portanto
nenhum movimento existe em base alguma. A migration é de esquema, e a Constituição não é tocada.
"""

# Generated by Django 5.2.17 on 2026-09-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocupacao", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="movimentodevaga",
            name="ck_movimento_inscricao_conforme_especie",
        ),
        migrations.RemoveField(
            model_name="movimentodevaga",
            name="inscricao",
        ),
        migrations.AlterField(
            model_name="movimentodevaga",
            name="especie",
            field=models.CharField(
                choices=[("REVERSAO_DE_COTA", "Reversão de cota")], max_length=32
            ),
        ),
    ]
