"""A quinta linha legítima do Resultado: o sucessor por regularização (019, `R-005`, `D-008`).

**A constraint foi estendida, e não afrouxada.** `ck_resultado_origem` tinha quatro linhas, e a
docstring do modelo diz que a `decisao` é *"a fonte jurídica do sucessor, obrigatória em todo
sucessor, qualquer que seja a origem"*. Admitir sucessor sem fonte nenhuma destruiria a garantia que
ela existe para dar; acrescentar uma fonte nova a preserva.

**A fonte nova é o desfecho da convocação, e entra como identidade opaca.** Uma FK daqui para
`convocacao` inverteria a dependência no grafo de migrations, e `resultados` deixaria de migrar sem
a `019`. A integridade referencial vem do outro lado: `DesfechoDaConvocacao.resultado_sucessor` é FK
para esta tabela, e os dois nascem na mesma transação.

**O gatilho ganha o ramo correspondente**, e a conferência da decisão passa a correr só quando há
decisão. Sem essa guarda o sucessor por regularização seria recusado com a mensagem errada —
acusando decisão de outra inscrição onde não há decisão nenhuma.
"""

# Generated by Django 5.2.17 on 2026-09-13 03:01

from django.db import migrations, models

CONFERIR = """
CREATE OR REPLACE FUNCTION check_stage_result_source() RETURNS trigger AS $$
DECLARE
    fonte RECORD;
    superado RECORD;
    julgado RECORD;
    edital_da_versao UUID;
BEGIN
    -- ── A cadeia, conferida antes da origem: ela vale para as três ───────────────────────────
    IF NEW.resultado_anterior_id IS NOT NULL THEN
        SELECT r.inscricao_id, r.etapa_id, r.edital_id, r.consolidado_em, r.avaliacao_id
          INTO superado
          FROM resultados_resultadoetapa r
         WHERE r.id = NEW.resultado_anterior_id;
        IF NOT FOUND
           OR superado.inscricao_id IS DISTINCT FROM NEW.inscricao_id
           OR superado.etapa_id IS DISTINCT FROM NEW.etapa_id
           OR superado.edital_id IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result supersedes a result of another registration or stage';
        END IF;
        IF EXISTS (
            SELECT 1 FROM resultados_resultadoetapa s
             WHERE s.resultado_anterior_id = NEW.resultado_anterior_id
        ) THEN
            RAISE EXCEPTION 'stage result supersedes a result that already has a successor';
        END IF;
        IF NEW.consolidado_em <= superado.consolidado_em THEN
            RAISE EXCEPTION 'stage result is not later than the result it supersedes';
        END IF;
        IF NEW.avaliacao_id IS NOT NULL
           AND NEW.avaliacao_id IS NOT DISTINCT FROM superado.avaliacao_id THEN
            RAISE EXCEPTION 'stage result reuses the source evaluation of the result it supersedes';
        END IF;

        -- **Todo sucessor cita uma fonte jurídica, e desde a `019` há duas** — a decisão
        -- recursal e o desfecho de convocação. `ck_sucessor_cita_decisao` exige exatamente uma
        -- delas; o que muda aqui é que as conferências da decisão só correm onde é ela a fonte.
        -- Sem esta guarda, o sucessor por regularização seria recusado com a mensagem errada,
        -- acusando decisão de outra inscrição onde não há decisão nenhuma.
        --
        -- **A guarda é pela origem, e não por `decisao_id IS NOT NULL`.** Testar a coluna deixaria
        -- o sucessor por recurso **sem** decisão atravessar este bloco sem carregar `julgado` — e a
        -- recusa sairia lá embaixo como "record julgado is not assigned yet", que não diz nada a
        -- quem a lê. Pela origem, a decisão continua obrigatória em todo sucessor que não seja
        -- regularização, e a mensagem continua sendo a que a `018` escreveu.
        IF NEW.origem <> 'REGULARIZACAO' THEN
        SELECT d.especie, d.consequencia, d.forma, d.pontuacao, d.sentido,
               d.versao_id, d.etapa_id, d.resultado_protegido_id, r.inscricao_id
          INTO julgado
          FROM recursos_decisaorecurso d
          JOIN recursos_recurso r ON r.id = d.recurso_id
         WHERE d.id = NEW.decisao_id;
        IF NOT FOUND
           OR julgado.inscricao_id IS DISTINCT FROM NEW.inscricao_id
           OR julgado.etapa_id IS DISTINCT FROM NEW.etapa_id THEN
            RAISE EXCEPTION 'stage result cites a decision of another registration or stage';
        END IF;

        -- **O superado é exatamente o Resultado que a decisão protegeu.** Sem isto, a decisão e a
        -- superação poderiam apontar para linhas diferentes do mesmo par — e a *non reformatio*,
        -- que compara contra `resultado_protegido`, estaria comparando com o Resultado errado.
        IF julgado.resultado_protegido_id IS DISTINCT FROM NEW.resultado_anterior_id THEN
            RAISE EXCEPTION 'stage result supersedes a result its decision does not protect';
        END IF;

        IF NEW.origem = 'RECURSO' AND julgado.especie <> 'CORRECAO_FIXADA' THEN
            RAISE EXCEPTION 'stage result by appeal cites a decision that fixed no correction';
        END IF;
        IF NEW.origem = 'AVALIACAO' AND julgado.especie <> 'REAVALIACAO_DETERMINADA' THEN
            RAISE EXCEPTION 'stage result by evaluation succeeds without an ordered reassessment';
        END IF;
        END IF;

        -- **A versão do sucessor é do mesmo Edital da decisão** — e não a mesma versão dela.
        --
        -- Exigir identidade quebraria o caminho da reavaliação: entre decidir e reavaliar pode
        -- haver Retificação, e a nova Avaliação carregaria outra `VersaoConsolidada`. A D-005 da
        -- 013 é explícita — "Versões Consolidadas diferentes podem descrever a mesma regra da
        -- Etapa", e a compatibilidade compara **conteúdo**, não identidade de linha. Como a
        -- decisão é imutável e não há como redecidir, a identidade produziria um sucessor
        -- permanentemente inconsolidável: o beco que este desenho existe para evitar.
        --
        -- Para a origem RECURSO a identidade **é** exigida, logo abaixo, e ali ela é correta: a
        -- decisão fixou a conclusão sob aquela norma, e o Resultado a copia inteira.
        SELECT v.edital_id INTO edital_da_versao
          FROM publicacoes_versaoconsolidada v
         WHERE v.id = NEW.versao_id;
        IF NOT FOUND OR edital_da_versao IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result cites a consolidated version of another edital';
        END IF;
    END IF;

    -- ── Origem RECURSO: a decisão é a fonte, e não há Avaliação a conferir ───────────────────
    IF NEW.origem = 'RECURSO' THEN
        -- **A guarda vem antes de tudo neste ramo**, e ela não é redundante com
        -- `ck_resultado_origem`. O `CHECK` também recusa uma raiz por recurso, mas o gatilho
        -- `BEFORE INSERT` roda **antes** das constraints: sem esta linha, `julgado` estaria vazio
        -- — nunca foi carregado, porque o bloco da cadeia não rodou — e a recusa sairia com a
        -- mensagem errada, acusando divergência de consequência onde o problema é outro.
        IF NEW.resultado_anterior_id IS NULL THEN
            RAISE EXCEPTION 'stage result by appeal must supersede a previous result';
        END IF;
        IF NEW.avaliacao_id IS NOT NULL THEN
            RAISE EXCEPTION 'stage result by appeal must not cite a source evaluation';
        END IF;
        -- **A conclusão é copiada da decisão, e a trigger prova a cópia inteira.** Conferir só a
        -- consequência deixaria passar um sucessor que se diz deferido em 75 e grava 90 — e o
        -- Resultado é append-only: o erro entraria uma vez e ficaria, com a decisão ao lado
        -- dizendo outra coisa. É a FR-058 no banco, e não em promessa de comando.
        IF julgado.consequencia IS DISTINCT FROM NEW.consequencia
           OR julgado.forma IS DISTINCT FROM NEW.forma
           OR julgado.pontuacao IS DISTINCT FROM NEW.pontuacao
           OR julgado.sentido IS DISTINCT FROM NEW.sentido THEN
            RAISE EXCEPTION 'stage result by appeal does not reproduce its decision conclusion';
        END IF;
        IF julgado.versao_id IS DISTINCT FROM NEW.versao_id THEN
            RAISE EXCEPTION 'stage result by appeal does not cite the version of its decision';
        END IF;
        SELECT v.edital_id INTO edital_da_versao
          FROM publicacoes_versaoconsolidada v
         WHERE v.id = NEW.versao_id;
        IF NOT FOUND OR edital_da_versao IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result cites a consolidated version of another edital';
        END IF;
        RETURN NEW;
    END IF;

    -- ── Origem REGULARIZACAO: a fonte é o desfecho da convocação (019, R-005) ───────────────
    IF NEW.origem = 'REGULARIZACAO' THEN
        -- **A guarda vem antes de tudo**, pela razão que o ramo do recurso já registra: o gatilho
        -- roda antes das constraints, e sem ela a recusa sairia com a mensagem errada.
        IF NEW.resultado_anterior_id IS NULL THEN
            RAISE EXCEPTION 'stage result by regularization must supersede a previous result';
        END IF;
        IF NEW.avaliacao_id IS NOT NULL THEN
            RAISE EXCEPTION 'stage result by regularization must not cite a source evaluation';
        END IF;
        -- **Ninguém interpôs recurso aqui.** Citar uma decisão registraria um julgamento que não
        -- houve — o mesmo tipo de mentira que a `018` recusou ao proibir Resultado por recurso
        -- citando Avaliação inexistente.
        IF NEW.decisao_id IS NOT NULL THEN
            RAISE EXCEPTION 'stage result by regularization must not cite an appeal decision';
        END IF;
        IF NEW.desfecho_de_convocacao_id IS NULL THEN
            RAISE EXCEPTION 'stage result by regularization must cite the call outcome';
        END IF;
        -- **A regularização habilita, e é a única consequência que ela pode ter.** Quem corrigiu o
        -- que estava indeferido passou a atender ao requisito; um sucessor por regularização que
        -- eliminasse afirmaria que corrigir piorou a situação da pessoa.
        IF NEW.consequencia <> 'HABILITADA' THEN
            RAISE EXCEPTION 'stage result by regularization must habilitate';
        END IF;
        -- **O desfecho não é conferido por junção, e a ausência é a decisão.** Juntar com
        -- `convocacao_desfechodaconvocacao` faria a migration de `resultados` depender da tabela
        -- da `019` — invertendo, no grafo de migrations, a dependência que a feature inteira
        -- existe para manter num sentido só. A integridade referencial vem do outro lado:
        -- `DesfechoDaConvocacao.resultado_sucessor` é FK para esta tabela, e os dois nascem na
        -- mesma transação.
        SELECT v.edital_id INTO edital_da_versao
          FROM publicacoes_versaoconsolidada v
         WHERE v.id = NEW.versao_id;
        IF NOT FOUND OR edital_da_versao IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result cites a consolidated version of another edital';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.origem = 'OCORRENCIA' THEN
        -- A Ocorrência não tem fonte a conferir, e por isso o que se confere é a ausência dela:
        -- uma linha que se diz constatação e cita Avaliação afirma as duas coisas ao mesmo tempo.
        IF NEW.avaliacao_id IS NOT NULL THEN
            RAISE EXCEPTION 'stage result by occurrence must not cite a source evaluation';
        END IF;
        -- E a norma citada precisa ser deste Edital. Sem Avaliação não há de onde a versão vir
        -- copiada, então esta é a única conferência que sobra — e sem ela a proveniência do ramo
        -- por Ocorrência seria promessa de código, que é o que estas triggers existem para negar.
        SELECT v.edital_id INTO edital_da_versao
          FROM publicacoes_versaoconsolidada v
         WHERE v.id = NEW.versao_id;
        IF NOT FOUND OR edital_da_versao IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result cites a consolidated version of another edital';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.origem <> 'AVALIACAO' OR NEW.avaliacao_id IS NULL THEN
        RAISE EXCEPTION 'stage result does not match its source evaluation';
    END IF;

    SELECT a.estado, a.forma, a.pontuacao, a.sentido, a.versao_id,
           t.inscricao_id, t.etapa_id, t.edital_id, t.ativo
      INTO fonte
      FROM avaliacoes_avaliacao a
      JOIN avaliacoes_atribuicao t ON t.id = a.atribuicao_id
     WHERE a.id = NEW.avaliacao_id;

    IF NOT FOUND
       OR fonte.inscricao_id IS DISTINCT FROM NEW.inscricao_id
       OR fonte.etapa_id IS DISTINCT FROM NEW.etapa_id
       OR fonte.edital_id IS DISTINCT FROM NEW.edital_id
       OR fonte.forma IS DISTINCT FROM NEW.forma
       OR fonte.pontuacao IS DISTINCT FROM NEW.pontuacao
       OR fonte.sentido IS DISTINCT FROM NEW.sentido
       OR fonte.versao_id IS DISTINCT FROM NEW.versao_id
       OR fonte.estado <> 'CONCLUIDA'
       OR NOT fonte.ativo THEN
        RAISE EXCEPTION 'stage result does not match its source evaluation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

CONFERIR_ANTERIOR = """
CREATE OR REPLACE FUNCTION check_stage_result_source() RETURNS trigger AS $$
DECLARE
    fonte RECORD;
    superado RECORD;
    julgado RECORD;
    edital_da_versao UUID;
BEGIN
    -- ── A cadeia, conferida antes da origem: ela vale para as três ───────────────────────────
    IF NEW.resultado_anterior_id IS NOT NULL THEN
        SELECT r.inscricao_id, r.etapa_id, r.edital_id, r.consolidado_em, r.avaliacao_id
          INTO superado
          FROM resultados_resultadoetapa r
         WHERE r.id = NEW.resultado_anterior_id;
        IF NOT FOUND
           OR superado.inscricao_id IS DISTINCT FROM NEW.inscricao_id
           OR superado.etapa_id IS DISTINCT FROM NEW.etapa_id
           OR superado.edital_id IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result supersedes a result of another registration or stage';
        END IF;
        IF EXISTS (
            SELECT 1 FROM resultados_resultadoetapa s
             WHERE s.resultado_anterior_id = NEW.resultado_anterior_id
        ) THEN
            RAISE EXCEPTION 'stage result supersedes a result that already has a successor';
        END IF;
        IF NEW.consolidado_em <= superado.consolidado_em THEN
            RAISE EXCEPTION 'stage result is not later than the result it supersedes';
        END IF;
        IF NEW.avaliacao_id IS NOT NULL
           AND NEW.avaliacao_id IS NOT DISTINCT FROM superado.avaliacao_id THEN
            RAISE EXCEPTION 'stage result reuses the source evaluation of the result it supersedes';
        END IF;

        -- A decisão é obrigatória em todo sucessor (ck_sucessor_cita_decisao), e a espécie dela
        -- precisa corresponder ao caminho que produziu esta linha.
        SELECT d.especie, d.consequencia, d.forma, d.pontuacao, d.sentido,
               d.versao_id, d.etapa_id, d.resultado_protegido_id, r.inscricao_id
          INTO julgado
          FROM recursos_decisaorecurso d
          JOIN recursos_recurso r ON r.id = d.recurso_id
         WHERE d.id = NEW.decisao_id;
        IF NOT FOUND
           OR julgado.inscricao_id IS DISTINCT FROM NEW.inscricao_id
           OR julgado.etapa_id IS DISTINCT FROM NEW.etapa_id THEN
            RAISE EXCEPTION 'stage result cites a decision of another registration or stage';
        END IF;

        -- **O superado é exatamente o Resultado que a decisão protegeu.** Sem isto, a decisão e a
        -- superação poderiam apontar para linhas diferentes do mesmo par — e a *non reformatio*,
        -- que compara contra `resultado_protegido`, estaria comparando com o Resultado errado.
        IF julgado.resultado_protegido_id IS DISTINCT FROM NEW.resultado_anterior_id THEN
            RAISE EXCEPTION 'stage result supersedes a result its decision does not protect';
        END IF;

        IF NEW.origem = 'RECURSO' AND julgado.especie <> 'CORRECAO_FIXADA' THEN
            RAISE EXCEPTION 'stage result by appeal cites a decision that fixed no correction';
        END IF;
        IF NEW.origem = 'AVALIACAO' AND julgado.especie <> 'REAVALIACAO_DETERMINADA' THEN
            RAISE EXCEPTION 'stage result by evaluation succeeds without an ordered reassessment';
        END IF;

        -- **A versão do sucessor é do mesmo Edital da decisão** — e não a mesma versão dela.
        --
        -- Exigir identidade quebraria o caminho da reavaliação: entre decidir e reavaliar pode
        -- haver Retificação, e a nova Avaliação carregaria outra `VersaoConsolidada`. A D-005 da
        -- 013 é explícita — "Versões Consolidadas diferentes podem descrever a mesma regra da
        -- Etapa", e a compatibilidade compara **conteúdo**, não identidade de linha. Como a
        -- decisão é imutável e não há como redecidir, a identidade produziria um sucessor
        -- permanentemente inconsolidável: o beco que este desenho existe para evitar.
        --
        -- Para a origem RECURSO a identidade **é** exigida, logo abaixo, e ali ela é correta: a
        -- decisão fixou a conclusão sob aquela norma, e o Resultado a copia inteira.
        SELECT v.edital_id INTO edital_da_versao
          FROM publicacoes_versaoconsolidada v
         WHERE v.id = NEW.versao_id;
        IF NOT FOUND OR edital_da_versao IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result cites a consolidated version of another edital';
        END IF;
    END IF;

    -- ── Origem RECURSO: a decisão é a fonte, e não há Avaliação a conferir ───────────────────
    IF NEW.origem = 'RECURSO' THEN
        -- **A guarda vem antes de tudo neste ramo**, e ela não é redundante com
        -- `ck_resultado_origem`. O `CHECK` também recusa uma raiz por recurso, mas o gatilho
        -- `BEFORE INSERT` roda **antes** das constraints: sem esta linha, `julgado` estaria vazio
        -- — nunca foi carregado, porque o bloco da cadeia não rodou — e a recusa sairia com a
        -- mensagem errada, acusando divergência de consequência onde o problema é outro.
        IF NEW.resultado_anterior_id IS NULL THEN
            RAISE EXCEPTION 'stage result by appeal must supersede a previous result';
        END IF;
        IF NEW.avaliacao_id IS NOT NULL THEN
            RAISE EXCEPTION 'stage result by appeal must not cite a source evaluation';
        END IF;
        -- **A conclusão é copiada da decisão, e a trigger prova a cópia inteira.** Conferir só a
        -- consequência deixaria passar um sucessor que se diz deferido em 75 e grava 90 — e o
        -- Resultado é append-only: o erro entraria uma vez e ficaria, com a decisão ao lado
        -- dizendo outra coisa. É a FR-058 no banco, e não em promessa de comando.
        IF julgado.consequencia IS DISTINCT FROM NEW.consequencia
           OR julgado.forma IS DISTINCT FROM NEW.forma
           OR julgado.pontuacao IS DISTINCT FROM NEW.pontuacao
           OR julgado.sentido IS DISTINCT FROM NEW.sentido THEN
            RAISE EXCEPTION 'stage result by appeal does not reproduce its decision conclusion';
        END IF;
        IF julgado.versao_id IS DISTINCT FROM NEW.versao_id THEN
            RAISE EXCEPTION 'stage result by appeal does not cite the version of its decision';
        END IF;
        SELECT v.edital_id INTO edital_da_versao
          FROM publicacoes_versaoconsolidada v
         WHERE v.id = NEW.versao_id;
        IF NOT FOUND OR edital_da_versao IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result cites a consolidated version of another edital';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.origem = 'OCORRENCIA' THEN
        -- A Ocorrência não tem fonte a conferir, e por isso o que se confere é a ausência dela:
        -- uma linha que se diz constatação e cita Avaliação afirma as duas coisas ao mesmo tempo.
        IF NEW.avaliacao_id IS NOT NULL THEN
            RAISE EXCEPTION 'stage result by occurrence must not cite a source evaluation';
        END IF;
        -- E a norma citada precisa ser deste Edital. Sem Avaliação não há de onde a versão vir
        -- copiada, então esta é a única conferência que sobra — e sem ela a proveniência do ramo
        -- por Ocorrência seria promessa de código, que é o que estas triggers existem para negar.
        SELECT v.edital_id INTO edital_da_versao
          FROM publicacoes_versaoconsolidada v
         WHERE v.id = NEW.versao_id;
        IF NOT FOUND OR edital_da_versao IS DISTINCT FROM NEW.edital_id THEN
            RAISE EXCEPTION 'stage result cites a consolidated version of another edital';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.origem <> 'AVALIACAO' OR NEW.avaliacao_id IS NULL THEN
        RAISE EXCEPTION 'stage result does not match its source evaluation';
    END IF;

    SELECT a.estado, a.forma, a.pontuacao, a.sentido, a.versao_id,
           t.inscricao_id, t.etapa_id, t.edital_id, t.ativo
      INTO fonte
      FROM avaliacoes_avaliacao a
      JOIN avaliacoes_atribuicao t ON t.id = a.atribuicao_id
     WHERE a.id = NEW.avaliacao_id;

    IF NOT FOUND
       OR fonte.inscricao_id IS DISTINCT FROM NEW.inscricao_id
       OR fonte.etapa_id IS DISTINCT FROM NEW.etapa_id
       OR fonte.edital_id IS DISTINCT FROM NEW.edital_id
       OR fonte.forma IS DISTINCT FROM NEW.forma
       OR fonte.pontuacao IS DISTINCT FROM NEW.pontuacao
       OR fonte.sentido IS DISTINCT FROM NEW.sentido
       OR fonte.versao_id IS DISTINCT FROM NEW.versao_id
       OR fonte.estado <> 'CONCLUIDA'
       OR NOT fonte.ativo THEN
        RAISE EXCEPTION 'stage result does not match its source evaluation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def conferir(apps, schema_editor):
    # O gatilho é PostgreSQL puro. Fora dele a migration passa sem instalar nada, e os testes
    # que dependem da garantia são pulados — a mesma guarda das anteriores desta app.
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(CONFERIR)


def conferir_anterior(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(CONFERIR_ANTERIOR)


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacoes", "0003_sentido_restrito_aos_dois_valores"),
        ("inscricoes", "0004_valor_de_fato"),
        ("processos", "0002_teto_de_inscricoes"),
        ("publicacoes", "0008_remover_ancoras"),
        ("recursos", "0001_initial"),
        ("resultados", "0005_superacao"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resultadoetapa",
            name="ck_sucessor_cita_decisao",
        ),
        migrations.RemoveConstraint(
            model_name="resultadoetapa",
            name="ck_resultado_origem",
        ),
        migrations.AddField(
            model_name="resultadoetapa",
            name="desfecho_de_convocacao_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resultadoetapa",
            name="origem",
            field=models.CharField(
                choices=[
                    ("AVALIACAO", "Avaliacao"),
                    ("OCORRENCIA", "Ocorrencia"),
                    ("REGULARIZACAO", "Regularizacao"),
                    ("RECURSO", "Recurso"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="resultadoetapa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decisao__isnull", True),
                        ("desfecho_de_convocacao_id__isnull", True),
                        ("resultado_anterior__isnull", True),
                    ),
                    models.Q(
                        ("decisao__isnull", False),
                        ("desfecho_de_convocacao_id__isnull", True),
                        ("resultado_anterior__isnull", False),
                    ),
                    models.Q(
                        ("decisao__isnull", True),
                        ("desfecho_de_convocacao_id__isnull", False),
                        ("resultado_anterior__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_sucessor_cita_decisao",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultadoetapa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("avaliacao__isnull", False),
                        ("origem", "AVALIACAO"),
                        models.Q(("forma", ""), _negated=True),
                    ),
                    models.Q(
                        ("avaliacao__isnull", True),
                        ("forma", ""),
                        ("origem", "OCORRENCIA"),
                        ("resultado_anterior__isnull", True),
                    ),
                    models.Q(
                        ("avaliacao__isnull", True),
                        ("origem", "RECURSO"),
                        ("resultado_anterior__isnull", False),
                    ),
                    models.Q(
                        ("avaliacao__isnull", True),
                        ("origem", "REGULARIZACAO"),
                        ("resultado_anterior__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_resultado_origem",
            ),
        ),
        migrations.RunPython(conferir, conferir_anterior),
    ]
