# Generated by Django 5.2.17 on 2026-10-06 21:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("codigo", models.CharField(max_length=100, unique=True)),
                ("sigla", models.CharField(max_length=30)),
                ("nome", models.CharField(max_length=255)),
                ("cabecalho", models.JSONField(default=list)),
                ("local", models.CharField(max_length=120)),
                ("ativa", models.BooleanField(default=True)),
                ("registrada_em", models.DateTimeField()),
                ("alterada_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["sigla"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("codigo", ""), _negated=True),
                        name="ck_unidade_codigo_preenchido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("nome", ""), _negated=True),
                        name="ck_unidade_nome_preenchido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("local", ""), _negated=True),
                        name="ck_unidade_local_preenchido",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AutoridadeHabilitada",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cargo", models.CharField(max_length=255)),
                ("nome", models.CharField(blank=True, default="", max_length=255)),
                ("ato_de_nomeacao", models.CharField(blank=True, default="", max_length=255)),
                ("inicio_vigencia", models.DateField()),
                ("fim_vigencia", models.DateField(blank=True, null=True)),
                ("cadastrada_por", models.CharField(max_length=255)),
                ("cadastrada_em", models.DateTimeField()),
                ("encerrada_por", models.CharField(blank=True, default="", max_length=255)),
                ("encerrada_em", models.DateTimeField(blank=True, null=True)),
                ("usada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autoridades",
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "ordering": ["cargo", "nome"],
                "indexes": [
                    models.Index(
                        fields=["unidade", "inicio_vigencia"], name="unidades_au_unidade_61ccf7_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cargo", ""), _negated=True),
                        name="ck_autoridade_cargo_preenchido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fim_vigencia__isnull", True),
                            ("fim_vigencia__gte", models.F("inicio_vigencia")),
                            _connector="OR",
                        ),
                        name="ck_autoridade_fim_depois_do_inicio",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("encerrada_em__isnull", True), ("encerrada_por", "")),
                            models.Q(
                                ("encerrada_em__isnull", False),
                                ("fim_vigencia__isnull", False),
                                models.Q(("encerrada_por", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_autoridade_encerramento_completo",
                    ),
                ],
            },
        ),
    ]
