"""A declaração expressa de encerramento do prazo recursal (018, FR-085, FR-086).

Três campos e uma constraint que os mantém inteiros: uma declaração com autor e sem fundamento é
afirmação sem razão escrita, e uma com fundamento e sem autor é razão sem quem responda por ela.

Ela existe **somente** onde o Edital não declarou janela recursal computável. Onde declarou, o
sistema verifica, e exigir a declaração ali seria pedir à pessoa que respondesse pelo que a máquina
sabe — a mesma afirmação sem lastro que o E2E17-005 registrou.
"""

# Generated by Django 5.2.17 on 2026-09-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classificacao", "0004_citacao"),
        ("divulgacao", "0001_initial"),
        ("processos", "0002_teto_de_inscricoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacaoresultado",
            name="prazo_encerrado_declarado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicacaoresultado",
            name="prazo_encerrado_declarado_por",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="publicacaoresultado",
            name="prazo_encerrado_fundamento",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="publicacaoresultado",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("prazo_encerrado_declarado_em__isnull", True),
                        ("prazo_encerrado_declarado_por", ""),
                        ("prazo_encerrado_fundamento", ""),
                    ),
                    models.Q(
                        ("prazo_encerrado_declarado_em__isnull", False),
                        models.Q(("prazo_encerrado_declarado_por", ""), _negated=True),
                        models.Q(("prazo_encerrado_fundamento", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_declaracao_completa",
            ),
        ),
    ]
