"""Os quatro modelos da 012, numa migration só.

A conclusão preservada é append-only no banco, e não só no agregado — pelo mesmo motivo que levou a
`003` a descer a imutabilidade do histórico normativo até a trigger: um `QuerySet.update()`
distraído, um script de manutenção ou acesso administrativo direto reescreveriam o que uma pessoa
concluiu antes de a presidência reabrir. O que sustenta "reabrir não destrói o que foi concluído"
não pode depender de todo caminho futuro lembrar de conferir (012, FR-094).

A trigger é condicional ao vendor, como a da `007` de `publicacoes`: em SQLite ela não existe, e é
por isso que os testes de garantia de banco são marcados `postgresql_only`.
"""

# Generated by Django 5.2.17 on 2026-09-01 23:26

import uuid

import django.db.models.deletion
from django.db import migrations, models

PROTEGER = """
CREATE FUNCTION reject_evaluation_conclusion_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'evaluation conclusions are append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER conclusao_avaliacao_append_only
BEFORE UPDATE OR DELETE ON avaliacoes_conclusaoavaliacao
FOR EACH ROW EXECUTE FUNCTION reject_evaluation_conclusion_mutation();
"""

DESPROTEGER = """
DROP TRIGGER IF EXISTS conclusao_avaliacao_append_only ON avaliacoes_conclusaoavaliacao;
DROP FUNCTION IF EXISTS reject_evaluation_conclusion_mutation();
"""


def proteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROTEGER)


def desproteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DESPROTEGER)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comissoes", "0001_initial"),
        ("inscricoes", "0002_documento_submetido"),
        ("processos", "0001_initial"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atribuicao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("etapa_id", models.UUIDField()),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField()),
                ("criado_por", models.CharField(max_length=255)),
                ("inativado_em", models.DateTimeField(blank=True, null=True)),
                ("inativado_por", models.CharField(blank=True, max_length=255)),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes",
                        to="processos.edital",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes",
                        to="inscricoes.inscricao",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes",
                        to="comissoes.membrocomissao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identity_subject", models.CharField(max_length=255)),
                ("etapa_id", models.UUIDField()),
                ("inscricao_id", models.UUIDField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("CONCLUIDA", "Concluida")],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                (
                    "pontuacao",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                ("parecer", models.TextField(blank=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("concluida_por", models.CharField(blank=True, max_length=255)),
                (
                    "atribuicao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacao",
                        to="avaliacoes.atribuicao",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConclusaoAvaliacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                ("pontuacao", models.DecimalField(decimal_places=4, max_digits=7)),
                ("parecer", models.TextField(blank=True)),
                ("concluida_em", models.DateTimeField()),
                ("concluida_por", models.CharField(max_length=255)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conclusoes",
                        to="avaliacoes.avaliacao",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conclusoes_de_avaliacao",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
            options={
                "ordering": ["avaliacao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Impedimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identity_subject", models.CharField(max_length=255)),
                ("motivo", models.TextField()),
                ("criado_em", models.DateTimeField()),
                ("criado_por", models.CharField(max_length=255)),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impedimentos",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="atribuicao",
            index=models.Index(
                fields=["edital", "etapa_id", "ativo"], name="avaliacoes__edital__7850f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atribuicao",
            index=models.Index(
                fields=["membro", "edital", "etapa_id", "ativo"],
                name="avaliacoes__membro__7743cc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="atribuicao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("membro", "edital", "etapa_id", "inscricao"),
                name="uq_atribuicao_ativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="atribuicao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ativo", True), ("inativado_em__isnull", True)),
                    models.Q(("ativo", False), ("inativado_em__isnull", False)),
                    _connector="OR",
                ),
                name="ck_atribuicao_inativacao_completa",
            ),
        ),
        migrations.AddIndex(
            model_name="avaliacao",
            index=models.Index(
                fields=["identity_subject", "etapa_id", "estado"],
                name="avaliacoes__identit_9a5b19_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="avaliacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "CONCLUIDA")),
                fields=("identity_subject", "etapa_id", "inscricao_id"),
                name="uq_avaliacao_concluida_por_pessoa",
            ),
        ),
        migrations.AddConstraint(
            model_name="avaliacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado", "RASCUNHO"),
                    models.Q(
                        ("concluida_em__isnull", False),
                        ("estado", "CONCLUIDA"),
                        ("pontuacao__isnull", False),
                        ("versao__isnull", False),
                        models.Q(("concluida_por", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_avaliacao_concluida_completa",
            ),
        ),
        migrations.AddConstraint(
            model_name="conclusaoavaliacao",
            constraint=models.UniqueConstraint(
                fields=("avaliacao", "ordem"), name="uq_conclusao_ordem"
            ),
        ),
        migrations.AddIndex(
            model_name="impedimento",
            index=models.Index(fields=["inscricao"], name="avaliacoes__inscric_5db120_idx"),
        ),
        migrations.AddConstraint(
            model_name="impedimento",
            constraint=models.UniqueConstraint(
                fields=("identity_subject", "inscricao"), name="uq_impedimento_pessoa_inscricao"
            ),
        ),
        migrations.RunPython(proteger, desproteger),
    ]
