# Generated by Django 5.2.17 on 2026-09-09 13:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classificacao", "0005_origem_e_lista"),
        ("inscricoes", "0004_valor_de_fato"),
        ("processos", "0002_teto_de_inscricoes"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcorrenciaDaFonte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fonte", models.CharField(max_length=255)),
                ("referencia", models.CharField(max_length=255)),
                ("material_bruto", models.TextField()),
                ("observada_em", models.DateTimeField()),
                ("observada_por", models.CharField(max_length=255)),
                ("indisponivel", models.BooleanField(default=False)),
                ("evidencia", models.TextField(blank=True, default="")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fonte", "referencia"), name="uq_ocorrencia_por_fonte"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("indisponivel", False),
                            models.Q(("evidencia", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="ck_indisponibilidade_com_evidencia",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RelacaoDeHabilitados",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("perfil_id", models.UUIDField()),
                ("marco_id", models.UUIDField()),
                ("lista_id", models.UUIDField(blank=True, null=True)),
                ("metodo_hash", models.CharField(max_length=64)),
                ("criterio_de_projecao", models.TextField()),
                ("quantidade", models.PositiveIntegerField()),
                ("resumo", models.CharField(db_index=True, max_length=64)),
                ("publicada_em", models.DateTimeField()),
                ("publicada_por", models.CharField(max_length=255)),
                ("motivo_da_sucessao", models.TextField(blank=True, default="")),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relacoes_de_sorteio",
                        to="processos.edital",
                    ),
                ),
                (
                    "relacao_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucessoras",
                        to="sorteios.relacaodehabilitados",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relacoes_de_sorteio",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipanteHabilitado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("numero_publico", models.PositiveIntegerField()),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes_em_sorteio",
                        to="inscricoes.inscricao",
                    ),
                ),
                (
                    "relacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="sorteios.relacaodehabilitados",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sorteio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("perfil_id", models.UUIDField()),
                ("marco_id", models.UUIDField()),
                ("lista_id", models.UUIDField(blank=True, null=True)),
                ("metodo_hash", models.CharField(max_length=64)),
                ("semente_normalizada", models.CharField(max_length=255)),
                ("manifesto_hash", models.CharField(max_length=64)),
                ("executado_em", models.DateTimeField()),
                ("executado_por", models.CharField(max_length=255)),
                ("motivo_da_anulacao", models.TextField(blank=True, default="")),
                (
                    "ato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorteio",
                        to="classificacao.atodeordenacao",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorteios",
                        to="processos.edital",
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorteios",
                        to="sorteios.ocorrenciadafonte",
                    ),
                ),
                (
                    "relacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorteios",
                        to="sorteios.relacaodehabilitados",
                    ),
                ),
                (
                    "sorteio_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucessores",
                        to="sorteios.sorteio",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="relacaodehabilitados",
            index=models.Index(
                fields=["edital", "perfil_id", "marco_id", "lista_id"],
                name="sorteios_re_edital__266480_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="relacaodehabilitados",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lista_id__isnull", True), ("relacao_anterior__isnull", True)),
                fields=("edital", "perfil_id", "marco_id"),
                name="uq_relacao_raiz_por_marco",
            ),
        ),
        migrations.AddConstraint(
            model_name="relacaodehabilitados",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lista_id__isnull", False), ("relacao_anterior__isnull", True)),
                fields=("edital", "perfil_id", "marco_id", "lista_id"),
                name="uq_relacao_raiz_por_marco_e_lista",
            ),
        ),
        migrations.AddConstraint(
            model_name="relacaodehabilitados",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relacao_anterior__isnull", False)),
                fields=("relacao_anterior",),
                name="uq_relacao_sucessora_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="relacaodehabilitados",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("relacao_anterior__isnull", True),
                    models.Q(("motivo_da_sucessao", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_relacao_sucessao_com_motivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="relacaodehabilitados",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gte", 1)), name="ck_relacao_nao_vazia"
            ),
        ),
        migrations.AddIndex(
            model_name="participantehabilitado",
            index=models.Index(
                fields=["relacao", "numero_publico"], name="sorteios_pa_relacao_bfee09_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participantehabilitado",
            constraint=models.UniqueConstraint(
                fields=("relacao", "inscricao"), name="uq_participante_por_relacao"
            ),
        ),
        migrations.AddConstraint(
            model_name="participantehabilitado",
            constraint=models.UniqueConstraint(
                fields=("relacao", "numero_publico"), name="uq_numero_por_relacao"
            ),
        ),
        migrations.AddIndex(
            model_name="sorteio",
            index=models.Index(
                fields=["edital", "perfil_id", "marco_id", "lista_id"],
                name="sorteios_so_edital__7c0d22_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sorteio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sorteio_anterior__isnull", True)),
                fields=("relacao", "ocorrencia"),
                name="uq_sorteio_raiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="sorteio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sorteio_anterior__isnull", False)),
                fields=("sorteio_anterior",),
                name="uq_sorteio_sucessor_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="sorteio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sorteio_anterior__isnull", True),
                    models.Q(("motivo_da_anulacao", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_sorteio_sucessao_com_motivo",
            ),
        ),
    ]
