# Generated by Django 5.2.17 on 2026-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorteios", "0002_imutabilidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrenciadafonte",
            name="ocorrida_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
