"""As sete tabelas dos avisos, e as travas que as mantêm (066, data-model §1 e §4).

**Seis append-only, com gatilho e privilégio ausente** — duas camadas independentes, nenhuma
contornável em desenvolvimento. O `save()` do modelo é a terceira, e é a única que um
`QuerySet.update()` não atravessa. As seis entram em `seguranca/papeis.py::TABELAS_APPEND_ONLY` na
mesma leva, levando o total de 34 para 40: numa base já provisionada é preciso **rodar o comando de
novo** depois desta migration, porque privilégio não se concede a tabela que ainda não existia.

**O modelo de aviso muda, e não se exclui.** O gatilho dele é só de `DELETE`: editar e inativar são
`UPDATE` legítimos, e o que a trilha registra deles é o antes e o depois (`FR-1277`).
"""

# Generated by Django 5.2.17 on 2026-10-09 14:37

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

PROTEGER = """
CREATE FUNCTION rejeitar_mutacao_do_aviso() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'avisos e o registro do envio são imutáveis';
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION rejeitar_exclusao_do_modelo_de_aviso() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'modelo de aviso não se exclui: inative-o';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aviso_append_only
BEFORE UPDATE OR DELETE ON avisos_aviso
FOR EACH ROW EXECUTE FUNCTION rejeitar_mutacao_do_aviso();

CREATE TRIGGER publicacao_do_aviso_append_only
BEFORE UPDATE OR DELETE ON avisos_publicacaodoaviso
FOR EACH ROW EXECUTE FUNCTION rejeitar_mutacao_do_aviso();

CREATE TRIGGER destinatario_do_aviso_append_only
BEFORE UPDATE OR DELETE ON avisos_destinatariodoaviso
FOR EACH ROW EXECUTE FUNCTION rejeitar_mutacao_do_aviso();

CREATE TRIGGER tentativa_de_envio_append_only
BEFORE UPDATE OR DELETE ON avisos_tentativadeenvio
FOR EACH ROW EXECUTE FUNCTION rejeitar_mutacao_do_aviso();

CREATE TRIGGER resultado_da_tentativa_append_only
BEFORE UPDATE OR DELETE ON avisos_resultadodatentativa
FOR EACH ROW EXECUTE FUNCTION rejeitar_mutacao_do_aviso();

CREATE TRIGGER interrupcao_do_aviso_append_only
BEFORE UPDATE OR DELETE ON avisos_interrupcaodoaviso
FOR EACH ROW EXECUTE FUNCTION rejeitar_mutacao_do_aviso();

CREATE TRIGGER modelo_de_aviso_nao_se_exclui
BEFORE DELETE ON avisos_modelodeaviso
FOR EACH ROW EXECUTE FUNCTION rejeitar_exclusao_do_modelo_de_aviso();
"""

DESPROTEGER = """
DROP TRIGGER IF EXISTS modelo_de_aviso_nao_se_exclui ON avisos_modelodeaviso;
DROP TRIGGER IF EXISTS interrupcao_do_aviso_append_only ON avisos_interrupcaodoaviso;
DROP TRIGGER IF EXISTS resultado_da_tentativa_append_only ON avisos_resultadodatentativa;
DROP TRIGGER IF EXISTS tentativa_de_envio_append_only ON avisos_tentativadeenvio;
DROP TRIGGER IF EXISTS destinatario_do_aviso_append_only ON avisos_destinatariodoaviso;
DROP TRIGGER IF EXISTS publicacao_do_aviso_append_only ON avisos_publicacaodoaviso;
DROP TRIGGER IF EXISTS aviso_append_only ON avisos_aviso;
DROP FUNCTION IF EXISTS rejeitar_exclusao_do_modelo_de_aviso();
DROP FUNCTION IF EXISTS rejeitar_mutacao_do_aviso();
"""


def proteger(apps, schema_editor):
    # PostgreSQL puro. Fora dele a migration passa sem instalar nada, e os testes que dependem da
    # garantia são pulados — a mesma guarda da `016` e da `019`.
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROTEGER)


def desproteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DESPROTEGER)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("convocacao", "0004_referencia_da_publicacao"),
        ("divulgacao", "0004_unidade_e_ato_de_nomeacao"),
        ("inscricoes", "0006_valor_de_fato_append_only"),
        ("processos", "0004_metodo_de_sorteio_comum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("institution_scope", models.CharField(max_length=100)),
                (
                    "origem",
                    models.CharField(
                        choices=[("RESULTADO", "RESULTADO"), ("CHAMADA", "CHAMADA")], max_length=16
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("PRIMEIRO_AVISO", "PRIMEIRO_AVISO"),
                            ("REENVIO_DE_FALHAS", "REENVIO_DE_FALHAS"),
                            ("REENVIO_JUSTIFICADO", "REENVIO_JUSTIFICADO"),
                        ],
                        max_length=24,
                    ),
                ),
                ("justificativa", models.TextField(blank=True, default="")),
                ("perfil_id", models.UUIDField()),
                ("marco_id", models.UUIDField()),
                ("lista_id", models.UUIDField(blank=True, null=True)),
                (
                    "natureza",
                    models.CharField(
                        blank=True,
                        choices=[("PRELIMINAR", "PRELIMINAR"), ("DEFINITIVA", "DEFINITIVA")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("referencia_da_publicacao", models.TextField(blank=True, default="")),
                ("retificadora", models.BooleanField(default=False)),
                ("assunto", models.CharField(max_length=150)),
                ("corpo", models.TextField()),
                ("solicitado_por", models.CharField(max_length=255)),
                ("solicitado_em", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=128)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "aviso_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reenvios",
                        to="avisos.aviso",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avisos",
                        to="processos.edital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DestinatarioDoAviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "elegibilidade",
                    models.CharField(
                        choices=[
                            ("ELEGIVEL", "ELEGIVEL"),
                            ("NAO_ELEGIVEL_DESFECHO", "NAO_ELEGIVEL_DESFECHO"),
                            ("NAO_ELEGIVEL_SUCEDIDA", "NAO_ELEGIVEL_SUCEDIDA"),
                            ("NAO_ELEGIVEL_VENCIDA", "NAO_ELEGIVEL_VENCIDA"),
                        ],
                        max_length=32,
                    ),
                ),
                ("endereco", models.CharField(blank=True, default="", max_length=255)),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destinatarios",
                        to="avisos.aviso",
                    ),
                ),
                (
                    "convocacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avisos",
                        to="convocacao.convocacao",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avisos",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterrupcaoDoAviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("motivo", models.TextField()),
                ("interrompido_por", models.CharField(max_length=255)),
                ("interrompido_em", models.DateTimeField()),
                (
                    "aviso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interrupcao",
                        to="avisos.aviso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModeloDeAviso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("institution_scope", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=120)),
                ("assunto", models.CharField(max_length=150)),
                ("corpo", models.TextField()),
                ("ativo", models.BooleanField(default=True)),
                ("modelo_inicial", models.BooleanField(default=False)),
                ("criado_por", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField()),
                ("alterado_por", models.CharField(blank=True, default="", max_length=255)),
                ("alterado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["institution_scope", "ativo"], name="ix_modelo_aviso_escopo"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("institution_scope"),
                        django.db.models.functions.text.Lower("nome"),
                        name="uq_modelo_de_aviso_nome_por_escopo",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="aviso",
            name="modelo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avisos",
                to="avisos.modelodeaviso",
            ),
        ),
        migrations.CreateModel(
            name="PublicacaoDoAviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publicacoes",
                        to="avisos.aviso",
                    ),
                ),
                (
                    "publicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avisos",
                        to="divulgacao.publicacaoresultado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TentativaDeEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("iniciada_em", models.DateTimeField()),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tentativas",
                        to="avisos.destinatariodoaviso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoDaTentativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("ACEITA", "ACEITA"),
                            ("FALHA_TEMPORARIA", "FALHA_TEMPORARIA"),
                            ("FALHA_DEFINITIVA", "FALHA_DEFINITIVA"),
                            ("INDETERMINADA", "INDETERMINADA"),
                        ],
                        max_length=24,
                    ),
                ),
                ("registrado_em", models.DateTimeField()),
                ("detalhe_tecnico", models.TextField(blank=True, default="")),
                (
                    "tentativa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultado",
                        to="avisos.tentativadeenvio",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="destinatariodoaviso",
            constraint=models.UniqueConstraint(
                fields=("aviso", "inscricao"), name="uq_destinatario_do_aviso"
            ),
        ),
        migrations.AddConstraint(
            model_name="destinatariodoaviso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "elegibilidade__in",
                        (
                            "ELEGIVEL",
                            "NAO_ELEGIVEL_DESFECHO",
                            "NAO_ELEGIVEL_SUCEDIDA",
                            "NAO_ELEGIVEL_VENCIDA",
                        ),
                    )
                ),
                name="ck_destinatario_elegibilidade",
            ),
        ),
        migrations.AddConstraint(
            model_name="interrupcaodoaviso",
            constraint=models.CheckConstraint(
                condition=models.Q(("motivo", ""), _negated=True),
                name="ck_interrupcao_do_aviso_com_motivo",
            ),
        ),
        migrations.AddIndex(
            model_name="aviso",
            index=models.Index(fields=["edital", "marco_id"], name="ix_aviso_edital_marco"),
        ),
        migrations.AddIndex(
            model_name="aviso",
            index=models.Index(fields=["solicitado_em"], name="ix_aviso_solicitado_em"),
        ),
        migrations.AddConstraint(
            model_name="aviso",
            constraint=models.CheckConstraint(
                condition=models.Q(("origem__in", ("RESULTADO", "CHAMADA"))),
                name="ck_aviso_origem_conhecida",
            ),
        ),
        migrations.AddConstraint(
            model_name="aviso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("motivo__in", ("PRIMEIRO_AVISO", "REENVIO_DE_FALHAS", "REENVIO_JUSTIFICADO"))
                ),
                name="ck_aviso_motivo_conhecido",
            ),
        ),
        migrations.AddConstraint(
            model_name="aviso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("natureza__in", ("PRELIMINAR", "DEFINITIVA")),
                        ("origem", "RESULTADO"),
                        ("referencia_da_publicacao", ""),
                    ),
                    models.Q(
                        ("natureza", ""),
                        ("origem", "CHAMADA"),
                        models.Q(("referencia_da_publicacao", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_aviso_ato_da_origem",
            ),
        ),
        migrations.AddConstraint(
            model_name="aviso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("motivo", "PRIMEIRO_AVISO"), ("aviso_anterior__isnull", False), _connector="OR"
                ),
                name="ck_aviso_reenvio_tem_anterior",
            ),
        ),
        migrations.AddConstraint(
            model_name="aviso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("motivo", "REENVIO_JUSTIFICADO"), _negated=True),
                    models.Q(("justificativa", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_aviso_reenvio_justificado_tem_texto",
            ),
        ),
        migrations.AddIndex(
            model_name="publicacaodoaviso",
            index=models.Index(fields=["publicacao"], name="ix_publicacao_do_aviso"),
        ),
        migrations.AddConstraint(
            model_name="publicacaodoaviso",
            constraint=models.UniqueConstraint(
                fields=("aviso", "publicacao"), name="uq_publicacao_do_aviso"
            ),
        ),
        migrations.AddConstraint(
            model_name="tentativadeenvio",
            constraint=models.UniqueConstraint(
                fields=("destinatario", "numero"), name="uq_tentativa_de_envio"
            ),
        ),
        migrations.AddConstraint(
            model_name="resultadodatentativa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "resultado__in",
                        ("ACEITA", "FALHA_TEMPORARIA", "FALHA_DEFINITIVA", "INDETERMINADA"),
                    )
                ),
                name="ck_resultado_da_tentativa",
            ),
        ),
        migrations.RunPython(proteger, desproteger),
    ]
