# Generated by Django 5.2.17 on 2026-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classificacao", "0004_citacao"),
        ("processos", "0002_teto_de_inscricoes"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="atodeordenacao",
            name="uq_ato_raiz_por_marco",
        ),
        migrations.AddField(
            model_name="atodeordenacao",
            name="lista_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atodeordenacao",
            name="origem",
            field=models.CharField(
                choices=[
                    ("COMPUTADO", "Computado a partir de Etapas"),
                    ("SORTEIO", "Constituído por sorteio"),
                ],
                default="COMPUTADO",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="atodeordenacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ato_anterior__isnull", True), ("lista_id__isnull", True)),
                fields=("edital", "perfil_id", "marco_id"),
                name="uq_ato_raiz_por_marco",
            ),
        ),
        migrations.AddConstraint(
            model_name="atodeordenacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ato_anterior__isnull", True), ("lista_id__isnull", False)),
                fields=("edital", "perfil_id", "marco_id", "lista_id"),
                name="uq_ato_raiz_por_marco_e_lista",
            ),
        ),
    ]
