"""O corte e os seus itens — e as **duas** travas que os mantêm append-only (014, FR-223).

Trigger **e** privilégio ausente, duas camadas independentes, nenhuma contornável em
desenvolvimento. O `save()` do modelo é a terceira, e é a única que um `QuerySet.update()` não
atravessa — por isso ela não basta sozinha.

A trigger é **absoluta**, e não condicional como a do artefato congelado: o corte nasce imutável.
Sucessão e continuação criam linha nova; não existe transição legítima que altere uma linha
existente.

O privilégio é retirado por `provisionar_papeis`, e as duas tabelas entram em
`seguranca/papeis.py::TABELAS_APPEND_ONLY` na mesma leva. Numa base já provisionada é preciso
**rodar o comando de novo** depois desta migration: privilégio não se concede a tabela que ainda
não existia.
"""

# Generated by Django 5.2.17 on 2026-09-11 18:30

import uuid

import django.db.models.deletion
from django.db import migrations, models

PROTEGER = """
CREATE FUNCTION reject_cut_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'emitted cuts are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER corte_imutavel
BEFORE UPDATE OR DELETE ON classificacao_corte
FOR EACH ROW EXECUTE FUNCTION reject_cut_mutation();

CREATE TRIGGER item_do_corte_imutavel
BEFORE UPDATE OR DELETE ON classificacao_itemdocorte
FOR EACH ROW EXECUTE FUNCTION reject_cut_mutation();
"""

DESPROTEGER = """
DROP TRIGGER IF EXISTS item_do_corte_imutavel ON classificacao_itemdocorte;
DROP TRIGGER IF EXISTS corte_imutavel ON classificacao_corte;
DROP FUNCTION IF EXISTS reject_cut_mutation();
"""


def proteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROTEGER)


def desproteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DESPROTEGER)


class Migration(migrations.Migration):
    dependencies = [
        ("classificacao", "0005_origem_e_lista"),
        ("inscricoes", "0004_valor_de_fato"),
        ("processos", "0002_teto_de_inscricoes"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Corte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("perfil_id", models.UUIDField()),
                ("marco_id", models.UUIDField()),
                ("lista_id", models.UUIDField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True, default="")),
                ("etapa_governada_id", models.UUIDField(blank=True, null=True)),
                ("universo", models.JSONField(default=dict)),
                ("primeira_posicao", models.PositiveIntegerField()),
                ("ultima_posicao", models.PositiveIntegerField(blank=True, null=True)),
                ("emitido_por", models.CharField(max_length=255)),
                ("emitido_em", models.DateTimeField()),
                (
                    "ato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="classificacao.atodeordenacao",
                    ),
                ),
                (
                    "corte_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucessores",
                        to="classificacao.corte",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="processos.edital",
                    ),
                ),
                (
                    "faixa_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="continuacoes",
                        to="classificacao.corte",
                    ),
                ),
                (
                    "raiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faixas",
                        to="classificacao.corte",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemDoCorte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("posicao", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "consequencia",
                    models.CharField(
                        choices=[("PROGREDIU", "Progrediu"), ("FORA_DA_FAIXA", "Fora Da Faixa")],
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField(blank=True, default="")),
                ("excedente_por_empate", models.BooleanField(default=False)),
                (
                    "corte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="classificacao.corte",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_de_corte",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="corte",
            index=models.Index(
                fields=["edital", "perfil_id", "marco_id"], name="classificac_edital__d22e16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corte",
            index=models.Index(fields=["raiz"], name="classificac_raiz_id_ce0d89_idx"),
        ),
        migrations.AddIndex(
            model_name="corte",
            index=models.Index(
                fields=["edital", "etapa_governada_id"], name="classificac_edital__f73f08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("corte_anterior__isnull", True),
                    ("faixa_anterior__isnull", True),
                    ("lista_id__isnull", True),
                ),
                fields=("edital", "perfil_id", "marco_id"),
                name="uq_corte_raiz_por_marco",
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("corte_anterior__isnull", True),
                    ("faixa_anterior__isnull", True),
                    ("lista_id__isnull", False),
                ),
                fields=("edital", "perfil_id", "marco_id", "lista_id"),
                name="uq_corte_raiz_por_marco_e_lista",
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.UniqueConstraint(
                condition=models.Q(("corte_anterior__isnull", False)),
                fields=("corte_anterior",),
                name="uq_geracao_sucessora_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.UniqueConstraint(
                condition=models.Q(("faixa_anterior__isnull", False)),
                fields=("faixa_anterior",),
                name="uq_corte_continuacao_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("corte_anterior__isnull", False),
                    ("faixa_anterior__isnull", False),
                    _negated=True,
                ),
                name="ck_corte_sucessao_ou_continuacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("corte_anterior__isnull", True), ("raiz__isnull", True), _connector="OR"
                ),
                name="ck_corte_sucessao_e_raiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("faixa_anterior__isnull", True), ("raiz__isnull", False), _connector="OR"
                ),
                name="ck_corte_continuacao_tem_raiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="corte",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("corte_anterior__isnull", True), ("faixa_anterior__isnull", True)),
                    models.Q(("motivo", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_corte_com_motivo",
            ),
        ),
        migrations.AddIndex(
            model_name="itemdocorte",
            index=models.Index(
                fields=["corte", "consequencia"], name="classificac_corte_i_b2e4e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemdocorte",
            index=models.Index(fields=["inscricao"], name="classificac_inscric_b6d85e_idx"),
        ),
        migrations.AddConstraint(
            model_name="itemdocorte",
            constraint=models.UniqueConstraint(
                fields=("corte", "inscricao"), name="uq_item_por_corte_inscricao"
            ),
        ),
        migrations.RunPython(proteger, desproteger),
    ]
