# Generated by Django 5.2.17 on 2026-09-16 23:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("convocacao", "0004_referencia_da_publicacao"),
        ("inscricoes", "0004_valor_de_fato"),
        ("publicacoes", "0008_remover_ancoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenciaDeCep",
            fields=[
                ("cep", models.CharField(max_length=8, primary_key=True, serialize=False)),
                ("logradouro", models.CharField(blank=True, default="", max_length=255)),
                ("bairro", models.CharField(blank=True, default="", max_length=120)),
                ("municipio", models.CharField(max_length=120)),
                ("uf", models.CharField(max_length=2)),
                ("codigo_ibge", models.CharField(blank=True, default="", max_length=7)),
            ],
            options={
                "verbose_name": "referência de CEP",
                "verbose_name_plural": "referências de CEP",
            },
        ),
        migrations.CreateModel(
            name="RequerimentoDeMatricula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "RASCUNHO"), ("ENVIADO", "ENVIADO")],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("disponibilizado_em", models.DateTimeField()),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                ("data_de_nascimento", models.DateField()),
                ("municipio_natal", models.CharField(max_length=120)),
                ("uf_natal", models.CharField(max_length=2)),
                ("nacionalidade", models.CharField(max_length=60)),
                ("sexo", models.CharField(choices=[("F", "F"), ("M", "M")], max_length=1)),
                (
                    "cor_raca",
                    models.CharField(
                        choices=[
                            ("BRANCA", "BRANCA"),
                            ("PRETA", "PRETA"),
                            ("PARDA", "PARDA"),
                            ("AMARELA", "AMARELA"),
                            ("INDIGENA", "INDIGENA"),
                            ("NAO_DECLARADA", "NAO_DECLARADA"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("SOLTEIRO", "SOLTEIRO"),
                            ("CASADO", "CASADO"),
                            ("DIVORCIADO", "DIVORCIADO"),
                            ("VIUVO", "VIUVO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome_da_mae", models.CharField(blank=True, default="", max_length=255)),
                ("nome_do_pai", models.CharField(blank=True, default="", max_length=255)),
                ("rg", models.CharField(max_length=30)),
                ("rg_orgao_emissor", models.CharField(max_length=30)),
                ("rg_expedido_em", models.DateField()),
                ("telefone_celular", models.CharField(max_length=30)),
                ("necessidade_especifica", models.TextField(blank=True, default="")),
                (
                    "renda_familiar_faixa",
                    models.CharField(
                        choices=[
                            ("ATE_0_5", "ATE_0_5"),
                            ("DE_0_5_A_1", "DE_0_5_A_1"),
                            ("DE_1_A_1_5", "DE_1_A_1_5"),
                            ("DE_1_5_A_2_5", "DE_1_5_A_2_5"),
                            ("DE_2_5_A_3_5", "DE_2_5_A_3_5"),
                            ("ACIMA_DE_3_5", "ACIMA_DE_3_5"),
                            ("NAO_DECLARADA", "NAO_DECLARADA"),
                        ],
                        max_length=24,
                    ),
                ),
                ("cep", models.CharField(max_length=8)),
                ("logradouro", models.CharField(max_length=255)),
                ("numero", models.CharField(blank=True, default="", max_length=20)),
                ("complemento", models.CharField(blank=True, default="", max_length=120)),
                ("bairro", models.CharField(blank=True, default="", max_length=120)),
                ("municipio", models.CharField(max_length=120)),
                ("uf", models.CharField(max_length=2)),
                ("codigo_ibge", models.CharField(blank=True, default="", max_length=7)),
                ("endereco_conferido_por_referencia", models.BooleanField(default=False)),
                ("declaracao_hash", models.CharField(blank=True, default="", max_length=64)),
                ("declaracao_aceita_em", models.DateTimeField(blank=True, null=True)),
                (
                    "convocacao_autorizadora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requerimentos",
                        to="convocacao.convocacao",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requerimentos",
                        to="inscricoes.inscricao",
                    ),
                ),
                (
                    "requerimento_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucessores",
                        to="requerimentos.requerimentodematricula",
                    ),
                ),
                (
                    "versao_aceita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requerimentos_aceitos",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["inscricao", "status"], name="requeriment_inscric_61d8e4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("requerimento_anterior__isnull", True)),
                        fields=("inscricao",),
                        name="uq_requerimento_raiz_por_inscricao",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("requerimento_anterior__isnull", False)),
                        fields=("requerimento_anterior",),
                        name="uq_requerimento_sucessor_unico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("requerimento_anterior__isnull", True),
                            ("convocacao_autorizadora__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_requerimento_sucessor_autorizado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "RASCUNHO"),
                            models.Q(
                                ("declaracao_aceita_em__isnull", False),
                                ("enviado_em__isnull", False),
                                ("status", "ENVIADO"),
                                ("versao_aceita__isnull", False),
                                models.Q(("declaracao_hash", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_requerimento_enviado_completo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["RASCUNHO", "ENVIADO"])),
                        name="ck_requerimento_status",
                    ),
                ],
            },
        ),
    ]
