# Generated by Django 5.2.17 on 2026-09-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convocacao", "0004_referencia_da_publicacao"),
        ("inscricoes", "0004_valor_de_fato"),
        ("publicacoes", "0008_remover_ancoras"),
        ("requerimentos", "0002_imutabilidade_do_enviado"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="requerimentodematricula",
            name="ck_requerimento_enviado_completo",
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="cep",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="cor_raca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BRANCA", "BRANCA"),
                    ("PRETA", "PRETA"),
                    ("PARDA", "PARDA"),
                    ("AMARELA", "AMARELA"),
                    ("INDIGENA", "INDIGENA"),
                    ("NAO_DECLARADA", "NAO_DECLARADA"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="data_de_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOLTEIRO", "SOLTEIRO"),
                    ("CASADO", "CASADO"),
                    ("DIVORCIADO", "DIVORCIADO"),
                    ("VIUVO", "VIUVO"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="logradouro",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="municipio",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="municipio_natal",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="nacionalidade",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="rg",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="rg_expedido_em",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="rg_orgao_emissor",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="telefone_celular",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="uf",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="requerimentodematricula",
            name="uf_natal",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddConstraint(
            model_name="requerimentodematricula",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "RASCUNHO"),
                    models.Q(
                        ("data_de_nascimento__isnull", False),
                        ("declaracao_aceita_em__isnull", False),
                        ("enviado_em__isnull", False),
                        ("rg_expedido_em__isnull", False),
                        ("status", "ENVIADO"),
                        ("versao_aceita__isnull", False),
                        models.Q(("declaracao_hash", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_requerimento_enviado_completo",
            ),
        ),
    ]
