"""As três tabelas do recurso, suas 14 constraints e suas cinco triggers.

**Três triggers de imutabilidade, absolutas.** A peça, o juízo de admissibilidade e a decisão nascem
e não mudam mais — nem por quem tem privilégio. Não há ato em curso que legitime mutação: interpor,
admitir e julgar acontecem uma vez cada.

**Duas triggers de coerência, e são duas porque uma trigger não valida outra tabela.** O gatilho é
por tabela: `recurso_coerente` roda no `INSERT` do `Recurso`, e nenhuma linha de `DecisaoRecurso`
passa por ela. A coerência da decisão mora na decisão.

O que `recurso_coerente` confere:

1. **o objeto atacado pertence à Inscrição de quem recorre.** Sem isto, uma gravação direta ligaria
   a peça de uma pessoa ao Resultado de outra — e o `CHECK` de exatamente-um não vê a diferença,
   porque ele só olha as duas nulidades. Para a publicação, a pertinência é a do Edital e a do
   Perfil: publicação de outro Perfil não diz respeito a esta Inscrição;
2. **a versão citada é do Edital da Inscrição.** É a norma sob a qual a peça foi interposta, e uma
   versão de outro Edital tornaria a proveniência inútil.

O que `decisao_recurso_coerente` confere:

1. **o recurso citado está admitido.** Julgar o mérito do que não foi admitido inverte a ordem dos
   atos, e a FR-036 a proíbe. Um juízo negativo também não abre o mérito;
2. **`resultado_protegido`, quando há, é do mesmo par e Edital da Inscrição do recurso.** Ele é a
   referência contra a qual a *non reformatio* compara — inclusive na consolidação da reavaliação,
   muito depois. Um Resultado de outro par tornaria a comparação sem sentido;
3. **`etapa_id`, quando há, é a Etapa do `resultado_protegido`.** Os dois descrevem o mesmo par, e
   divergirem faria a decisão alcançar uma Etapa e proteger outra;
4. **a versão citada é do Edital do recurso.** O Resultado sucessor copia essa versão, de modo que
   uma versão alheia atravessaria para um registro que nada corrige depois.

As duas dependem de **outra linha**, e é por isso que são triggers e não `CheckConstraint`:
`CHECK` não atravessa tabelas em PostgreSQL.
"""

# Generated by Django 5.2.17 on 2026-09-07 00:07

import uuid

import django.db.models.deletion
from django.db import migrations, models

PROTEGER = """
CREATE OR REPLACE FUNCTION reject_appeal_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'appeals are append-only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER recurso_append_only
BEFORE UPDATE OR DELETE ON recursos_recurso
FOR EACH ROW EXECUTE FUNCTION reject_appeal_mutation();

CREATE OR REPLACE FUNCTION reject_admissibility_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'admissibility rulings are append-only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER juizo_de_admissibilidade_append_only
BEFORE UPDATE OR DELETE ON recursos_juizodeadmissibilidade
FOR EACH ROW EXECUTE FUNCTION reject_admissibility_mutation();

CREATE OR REPLACE FUNCTION reject_appeal_decision_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'appeal decisions are append-only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER decisao_recurso_append_only
BEFORE UPDATE OR DELETE ON recursos_decisaorecurso
FOR EACH ROW EXECUTE FUNCTION reject_appeal_decision_mutation();

CREATE OR REPLACE FUNCTION check_appeal_coherence() RETURNS trigger AS $$
DECLARE
    titular RECORD;
    alvo RECORD;
    edital_da_versao UUID;
BEGIN
    SELECT i.edital_id, i.profile_id
      INTO titular
      FROM inscricoes_inscricao i
     WHERE i.id = NEW.inscricao_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'appeal cites a registration that does not exist';
    END IF;

    IF NEW.resultado_atacado_id IS NOT NULL THEN
        SELECT r.inscricao_id
          INTO alvo
          FROM resultados_resultadoetapa r
         WHERE r.id = NEW.resultado_atacado_id;
        IF NOT FOUND OR alvo.inscricao_id IS DISTINCT FROM NEW.inscricao_id THEN
            RAISE EXCEPTION 'appeal attacks a stage result of another registration';
        END IF;
    ELSE
        SELECT p.edital_id, p.perfil_id
          INTO alvo
          FROM divulgacao_publicacaoresultado p
         WHERE p.id = NEW.publicacao_atacada_id;
        IF NOT FOUND
           OR alvo.edital_id IS DISTINCT FROM titular.edital_id
           OR alvo.perfil_id IS DISTINCT FROM titular.profile_id THEN
            RAISE EXCEPTION 'appeal attacks a publication that does not concern its registration';
        END IF;
    END IF;

    SELECT v.edital_id INTO edital_da_versao
      FROM publicacoes_versaoconsolidada v
     WHERE v.id = NEW.versao_id;
    IF NOT FOUND OR edital_da_versao IS DISTINCT FROM titular.edital_id THEN
        RAISE EXCEPTION 'appeal cites a consolidated version of another edital';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER recurso_coerente
BEFORE INSERT ON recursos_recurso
FOR EACH ROW EXECUTE FUNCTION check_appeal_coherence();

CREATE OR REPLACE FUNCTION check_appeal_decision_coherence() RETURNS trigger AS $$
DECLARE
    peca RECORD;
    protegido RECORD;
    edital_da_versao UUID;
BEGIN
    -- Julgar o mérito exige juízo de admissibilidade positivo. Receber a peça não é admiti-la.
    SELECT r.inscricao_id, i.edital_id
      INTO peca
      FROM recursos_recurso r
      JOIN inscricoes_inscricao i ON i.id = r.inscricao_id
     WHERE r.id = NEW.recurso_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'appeal decision cites an appeal that does not exist';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM recursos_juizodeadmissibilidade j
         WHERE j.recurso_id = NEW.recurso_id
           AND j.admitido
    ) THEN
        RAISE EXCEPTION 'appeal decision on an appeal that was not admitted';
    END IF;

    -- A norma sob a qual se decidiu precisa ser **deste** Edital. Uma versão alheia tornaria a
    -- proveniência da decisão inútil — e o Resultado sucessor copia essa versão, de modo que o
    -- erro atravessaria para um registro que nada corrige depois.
    SELECT v.edital_id INTO edital_da_versao
      FROM publicacoes_versaoconsolidada v
     WHERE v.id = NEW.versao_id;
    IF NOT FOUND OR edital_da_versao IS DISTINCT FROM peca.edital_id THEN
        RAISE EXCEPTION 'appeal decision cites a consolidated version of another edital';
    END IF;

    IF NEW.resultado_protegido_id IS NOT NULL THEN
        SELECT r.inscricao_id, r.etapa_id, r.edital_id
          INTO protegido
          FROM resultados_resultadoetapa r
         WHERE r.id = NEW.resultado_protegido_id;
        IF NOT FOUND
           OR protegido.inscricao_id IS DISTINCT FROM peca.inscricao_id
           OR protegido.edital_id IS DISTINCT FROM peca.edital_id THEN
            RAISE EXCEPTION 'appeal decision protects a stage result of another registration';
        END IF;
        IF NEW.etapa_id IS DISTINCT FROM protegido.etapa_id THEN
            RAISE EXCEPTION 'appeal decision reaches a stage other than the one it protects';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER decisao_recurso_coerente
BEFORE INSERT ON recursos_decisaorecurso
FOR EACH ROW EXECUTE FUNCTION check_appeal_decision_coherence();
"""

DESPROTEGER = """
DROP TRIGGER IF EXISTS decisao_recurso_coerente ON recursos_decisaorecurso;
DROP FUNCTION IF EXISTS check_appeal_decision_coherence();
DROP TRIGGER IF EXISTS recurso_coerente ON recursos_recurso;
DROP FUNCTION IF EXISTS check_appeal_coherence();
DROP TRIGGER IF EXISTS decisao_recurso_append_only ON recursos_decisaorecurso;
DROP FUNCTION IF EXISTS reject_appeal_decision_mutation();
DROP TRIGGER IF EXISTS juizo_de_admissibilidade_append_only ON recursos_juizodeadmissibilidade;
DROP FUNCTION IF EXISTS reject_admissibility_mutation();
DROP TRIGGER IF EXISTS recurso_append_only ON recursos_recurso;
DROP FUNCTION IF EXISTS reject_appeal_mutation();
"""


def proteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROTEGER)


def desproteger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DESPROTEGER)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("divulgacao", "0001_initial"),
        ("inscricoes", "0004_valor_de_fato"),
        ("publicacoes", "0008_remover_ancoras"),
        ("resultados", "0004_resultado_por_ocorrencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("protocolo", models.CharField(max_length=32, unique=True)),
                ("interposto_por", models.CharField(max_length=255)),
                ("interposto_em", models.DateTimeField()),
                ("fundamentacao", models.TextField()),
                ("janela_abriu_em", models.DateTimeField(blank=True, null=True)),
                ("janela_fecha_em", models.DateTimeField(blank=True, null=True)),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="inscricoes.inscricao",
                    ),
                ),
                (
                    "publicacao_atacada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="divulgacao.publicacaoresultado",
                    ),
                ),
                (
                    "resultado_atacado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="resultados.resultadoetapa",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JuizoDeAdmissibilidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("admitido", models.BooleanField()),
                ("motivo", models.TextField()),
                ("decidido_por", models.CharField(max_length=255)),
                ("decidido_em", models.DateTimeField()),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="juizos",
                        to="recursos.recurso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisaoRecurso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("INDEFERIDO", "Indeferido"),
                            ("CORRECAO_FIXADA", "Correcao Fixada"),
                            ("REAVALIACAO_DETERMINADA", "Reavaliacao Determinada"),
                            ("PROVIDENCIA_A_JUSANTE", "Providencia A Jusante"),
                        ],
                        max_length=30,
                    ),
                ),
                ("motivacao", models.TextField()),
                ("decidido_por", models.CharField(max_length=255)),
                ("decidido_em", models.DateTimeField()),
                ("etapa_id", models.UUIDField(blank=True, null=True)),
                (
                    "consequencia",
                    models.CharField(
                        blank=True,
                        choices=[("HABILITADA", "Habilitada"), ("ELIMINADA", "Eliminada")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "forma",
                    models.CharField(
                        blank=True,
                        choices=[("PONTUADA", "Pontuada"), ("DECISORIA", "Decisoria")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "pontuacao",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                (
                    "sentido",
                    models.CharField(
                        blank=True,
                        choices=[("FAVORAVEL", "Favoravel"), ("DESFAVORAVEL", "Desfavoravel")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "resultado_protegido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisoes_que_o_protegem",
                        to="resultados.resultadoetapa",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisoes_de_recurso",
                        to="publicacoes.versaoconsolidada",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisoes",
                        to="recursos.recurso",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="recurso",
            index=models.Index(fields=["inscricao"], name="recursos_re_inscric_fee74f_idx"),
        ),
        migrations.AddConstraint(
            model_name="recurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("publicacao_atacada__isnull", True), ("resultado_atacado__isnull", False)
                    ),
                    models.Q(
                        ("publicacao_atacada__isnull", False), ("resultado_atacado__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="ck_recurso_objeto_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurso",
            constraint=models.CheckConstraint(
                condition=models.Q(("fundamentacao", ""), _negated=True),
                name="ck_recurso_fundamentacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("janela_abriu_em__isnull", True), ("janela_fecha_em__isnull", True)),
                    models.Q(
                        ("janela_abriu_em__isnull", False), ("janela_fecha_em__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_recurso_janela_completa",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurso",
            constraint=models.UniqueConstraint(
                condition=models.Q(("publicacao_atacada__isnull", False)),
                fields=("inscricao", "publicacao_atacada"),
                name="uq_recurso_por_publicacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurso",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resultado_atacado__isnull", False)),
                fields=("inscricao", "resultado_atacado"),
                name="uq_recurso_por_resultado",
            ),
        ),
        migrations.AddConstraint(
            model_name="juizodeadmissibilidade",
            constraint=models.UniqueConstraint(fields=("recurso",), name="uq_juizo_por_recurso"),
        ),
        migrations.AddConstraint(
            model_name="juizodeadmissibilidade",
            constraint=models.CheckConstraint(
                condition=models.Q(("motivo", ""), _negated=True), name="ck_juizo_motivo"
            ),
        ),
        migrations.AddIndex(
            model_name="decisaorecurso",
            index=models.Index(fields=["especie"], name="recursos_de_especie_ab49ff_idx"),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.UniqueConstraint(fields=("recurso",), name="uq_decisao_por_recurso"),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(("motivacao", ""), _negated=True), name="ck_decisao_motivacao"
            ),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "especie__in",
                        (
                            "INDEFERIDO",
                            "CORRECAO_FIXADA",
                            "REAVALIACAO_DETERMINADA",
                            "PROVIDENCIA_A_JUSANTE",
                        ),
                    )
                ),
                name="ck_decisao_especie",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("especie", "CORRECAO_FIXADA"), _negated=True),
                    models.Q(
                        ("etapa_id__isnull", False),
                        ("resultado_protegido__isnull", False),
                        models.Q(("consequencia", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_decisao_correcao_completa",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("especie", "REAVALIACAO_DETERMINADA"), _negated=True),
                    models.Q(
                        ("consequencia", ""),
                        ("etapa_id__isnull", False),
                        ("resultado_protegido__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_decisao_reavaliacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("especie__in", ("INDEFERIDO", "PROVIDENCIA_A_JUSANTE")), _negated=True
                    ),
                    models.Q(("consequencia", ""), ("resultado_protegido__isnull", True)),
                    _connector="OR",
                ),
                name="ck_decisao_sem_efeito",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(("consequencia__in", ("", "HABILITADA", "ELIMINADA"))),
                name="ck_decisao_consequencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("forma", "PONTUADA"), ("pontuacao__isnull", False), ("sentido", "")),
                    models.Q(
                        ("forma", "DECISORIA"),
                        ("pontuacao__isnull", True),
                        ("sentido__in", ("FAVORAVEL", "DESFAVORAVEL")),
                    ),
                    models.Q(("forma", ""), ("pontuacao__isnull", True), ("sentido", "")),
                    _connector="OR",
                ),
                name="ck_decisao_conclusao_por_forma",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisaorecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("especie", "CORRECAO_FIXADA"),
                    models.Q(("forma", ""), ("pontuacao__isnull", True), ("sentido", "")),
                    _connector="OR",
                ),
                name="ck_decisao_sem_grandeza_residual",
            ),
        ),
        migrations.RunPython(proteger, desproteger),
    ]
